/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/consumption/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBudgetManagementGroups implements BudgetManagementGroupInterface
type FakeBudgetManagementGroups struct {
	Fake *FakeConsumptionV1alpha1
	ns   string
}

var budgetmanagementgroupsResource = schema.GroupVersionResource{Group: "consumption.azurerm.kubeform.com", Version: "v1alpha1", Resource: "budgetmanagementgroups"}

var budgetmanagementgroupsKind = schema.GroupVersionKind{Group: "consumption.azurerm.kubeform.com", Version: "v1alpha1", Kind: "BudgetManagementGroup"}

// Get takes name of the budgetManagementGroup, and returns the corresponding budgetManagementGroup object, and an error if there is any.
func (c *FakeBudgetManagementGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BudgetManagementGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(budgetmanagementgroupsResource, c.ns, name), &v1alpha1.BudgetManagementGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BudgetManagementGroup), err
}

// List takes label and field selectors, and returns the list of BudgetManagementGroups that match those selectors.
func (c *FakeBudgetManagementGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BudgetManagementGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(budgetmanagementgroupsResource, budgetmanagementgroupsKind, c.ns, opts), &v1alpha1.BudgetManagementGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BudgetManagementGroupList{ListMeta: obj.(*v1alpha1.BudgetManagementGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.BudgetManagementGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested budgetManagementGroups.
func (c *FakeBudgetManagementGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(budgetmanagementgroupsResource, c.ns, opts))

}

// Create takes the representation of a budgetManagementGroup and creates it.  Returns the server's representation of the budgetManagementGroup, and an error, if there is any.
func (c *FakeBudgetManagementGroups) Create(ctx context.Context, budgetManagementGroup *v1alpha1.BudgetManagementGroup, opts v1.CreateOptions) (result *v1alpha1.BudgetManagementGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(budgetmanagementgroupsResource, c.ns, budgetManagementGroup), &v1alpha1.BudgetManagementGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BudgetManagementGroup), err
}

// Update takes the representation of a budgetManagementGroup and updates it. Returns the server's representation of the budgetManagementGroup, and an error, if there is any.
func (c *FakeBudgetManagementGroups) Update(ctx context.Context, budgetManagementGroup *v1alpha1.BudgetManagementGroup, opts v1.UpdateOptions) (result *v1alpha1.BudgetManagementGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(budgetmanagementgroupsResource, c.ns, budgetManagementGroup), &v1alpha1.BudgetManagementGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BudgetManagementGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBudgetManagementGroups) UpdateStatus(ctx context.Context, budgetManagementGroup *v1alpha1.BudgetManagementGroup, opts v1.UpdateOptions) (*v1alpha1.BudgetManagementGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(budgetmanagementgroupsResource, "status", c.ns, budgetManagementGroup), &v1alpha1.BudgetManagementGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BudgetManagementGroup), err
}

// Delete takes name of the budgetManagementGroup and deletes it. Returns an error if one occurs.
func (c *FakeBudgetManagementGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(budgetmanagementgroupsResource, c.ns, name), &v1alpha1.BudgetManagementGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBudgetManagementGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(budgetmanagementgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BudgetManagementGroupList{})
	return err
}

// Patch applies the patch and returns the patched budgetManagementGroup.
func (c *FakeBudgetManagementGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BudgetManagementGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(budgetmanagementgroupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BudgetManagementGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BudgetManagementGroup), err
}
