/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AssetListerExpansion allows custom methods to be added to
// AssetLister.
type AssetListerExpansion interface{}

// AssetNamespaceListerExpansion allows custom methods to be added to
// AssetNamespaceLister.
type AssetNamespaceListerExpansion interface{}

// AssetFilterListerExpansion allows custom methods to be added to
// AssetFilterLister.
type AssetFilterListerExpansion interface{}

// AssetFilterNamespaceListerExpansion allows custom methods to be added to
// AssetFilterNamespaceLister.
type AssetFilterNamespaceListerExpansion interface{}

// ContentKeyPolicyListerExpansion allows custom methods to be added to
// ContentKeyPolicyLister.
type ContentKeyPolicyListerExpansion interface{}

// ContentKeyPolicyNamespaceListerExpansion allows custom methods to be added to
// ContentKeyPolicyNamespaceLister.
type ContentKeyPolicyNamespaceListerExpansion interface{}

// JobListerExpansion allows custom methods to be added to
// JobLister.
type JobListerExpansion interface{}

// JobNamespaceListerExpansion allows custom methods to be added to
// JobNamespaceLister.
type JobNamespaceListerExpansion interface{}

// LiveEventListerExpansion allows custom methods to be added to
// LiveEventLister.
type LiveEventListerExpansion interface{}

// LiveEventNamespaceListerExpansion allows custom methods to be added to
// LiveEventNamespaceLister.
type LiveEventNamespaceListerExpansion interface{}

// LiveEventOutputListerExpansion allows custom methods to be added to
// LiveEventOutputLister.
type LiveEventOutputListerExpansion interface{}

// LiveEventOutputNamespaceListerExpansion allows custom methods to be added to
// LiveEventOutputNamespaceLister.
type LiveEventOutputNamespaceListerExpansion interface{}

// ServicesAccountListerExpansion allows custom methods to be added to
// ServicesAccountLister.
type ServicesAccountListerExpansion interface{}

// ServicesAccountNamespaceListerExpansion allows custom methods to be added to
// ServicesAccountNamespaceLister.
type ServicesAccountNamespaceListerExpansion interface{}

// StreamingEndpointListerExpansion allows custom methods to be added to
// StreamingEndpointLister.
type StreamingEndpointListerExpansion interface{}

// StreamingEndpointNamespaceListerExpansion allows custom methods to be added to
// StreamingEndpointNamespaceLister.
type StreamingEndpointNamespaceListerExpansion interface{}

// StreamingLocatorListerExpansion allows custom methods to be added to
// StreamingLocatorLister.
type StreamingLocatorListerExpansion interface{}

// StreamingLocatorNamespaceListerExpansion allows custom methods to be added to
// StreamingLocatorNamespaceLister.
type StreamingLocatorNamespaceListerExpansion interface{}

// StreamingPolicyListerExpansion allows custom methods to be added to
// StreamingPolicyLister.
type StreamingPolicyListerExpansion interface{}

// StreamingPolicyNamespaceListerExpansion allows custom methods to be added to
// StreamingPolicyNamespaceLister.
type StreamingPolicyNamespaceListerExpansion interface{}

// TransformListerExpansion allows custom methods to be added to
// TransformLister.
type TransformListerExpansion interface{}

// TransformNamespaceListerExpansion allows custom methods to be added to
// TransformNamespaceLister.
type TransformNamespaceListerExpansion interface{}
