/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/app/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ServiceSlotVirtualNetworkSwiftConnectionLister helps list ServiceSlotVirtualNetworkSwiftConnections.
// All objects returned here must be treated as read-only.
type ServiceSlotVirtualNetworkSwiftConnectionLister interface {
	// List lists all ServiceSlotVirtualNetworkSwiftConnections in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ServiceSlotVirtualNetworkSwiftConnection, err error)
	// ServiceSlotVirtualNetworkSwiftConnections returns an object that can list and get ServiceSlotVirtualNetworkSwiftConnections.
	ServiceSlotVirtualNetworkSwiftConnections(namespace string) ServiceSlotVirtualNetworkSwiftConnectionNamespaceLister
	ServiceSlotVirtualNetworkSwiftConnectionListerExpansion
}

// serviceSlotVirtualNetworkSwiftConnectionLister implements the ServiceSlotVirtualNetworkSwiftConnectionLister interface.
type serviceSlotVirtualNetworkSwiftConnectionLister struct {
	indexer cache.Indexer
}

// NewServiceSlotVirtualNetworkSwiftConnectionLister returns a new ServiceSlotVirtualNetworkSwiftConnectionLister.
func NewServiceSlotVirtualNetworkSwiftConnectionLister(indexer cache.Indexer) ServiceSlotVirtualNetworkSwiftConnectionLister {
	return &serviceSlotVirtualNetworkSwiftConnectionLister{indexer: indexer}
}

// List lists all ServiceSlotVirtualNetworkSwiftConnections in the indexer.
func (s *serviceSlotVirtualNetworkSwiftConnectionLister) List(selector labels.Selector) (ret []*v1alpha1.ServiceSlotVirtualNetworkSwiftConnection, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ServiceSlotVirtualNetworkSwiftConnection))
	})
	return ret, err
}

// ServiceSlotVirtualNetworkSwiftConnections returns an object that can list and get ServiceSlotVirtualNetworkSwiftConnections.
func (s *serviceSlotVirtualNetworkSwiftConnectionLister) ServiceSlotVirtualNetworkSwiftConnections(namespace string) ServiceSlotVirtualNetworkSwiftConnectionNamespaceLister {
	return serviceSlotVirtualNetworkSwiftConnectionNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ServiceSlotVirtualNetworkSwiftConnectionNamespaceLister helps list and get ServiceSlotVirtualNetworkSwiftConnections.
// All objects returned here must be treated as read-only.
type ServiceSlotVirtualNetworkSwiftConnectionNamespaceLister interface {
	// List lists all ServiceSlotVirtualNetworkSwiftConnections in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ServiceSlotVirtualNetworkSwiftConnection, err error)
	// Get retrieves the ServiceSlotVirtualNetworkSwiftConnection from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ServiceSlotVirtualNetworkSwiftConnection, error)
	ServiceSlotVirtualNetworkSwiftConnectionNamespaceListerExpansion
}

// serviceSlotVirtualNetworkSwiftConnectionNamespaceLister implements the ServiceSlotVirtualNetworkSwiftConnectionNamespaceLister
// interface.
type serviceSlotVirtualNetworkSwiftConnectionNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ServiceSlotVirtualNetworkSwiftConnections in the indexer for a given namespace.
func (s serviceSlotVirtualNetworkSwiftConnectionNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ServiceSlotVirtualNetworkSwiftConnection, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ServiceSlotVirtualNetworkSwiftConnection))
	})
	return ret, err
}

// Get retrieves the ServiceSlotVirtualNetworkSwiftConnection from the indexer for a given namespace and name.
func (s serviceSlotVirtualNetworkSwiftConnectionNamespaceLister) Get(name string) (*v1alpha1.ServiceSlotVirtualNetworkSwiftConnection, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("serviceslotvirtualnetworkswiftconnection"), name)
	}
	return obj.(*v1alpha1.ServiceSlotVirtualNetworkSwiftConnection), nil
}
