/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/iottime/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSeriesInsightsAccessPolicies implements SeriesInsightsAccessPolicyInterface
type FakeSeriesInsightsAccessPolicies struct {
	Fake *FakeIottimeV1alpha1
	ns   string
}

var seriesinsightsaccesspoliciesResource = schema.GroupVersionResource{Group: "iottime.azurerm.kubeform.com", Version: "v1alpha1", Resource: "seriesinsightsaccesspolicies"}

var seriesinsightsaccesspoliciesKind = schema.GroupVersionKind{Group: "iottime.azurerm.kubeform.com", Version: "v1alpha1", Kind: "SeriesInsightsAccessPolicy"}

// Get takes name of the seriesInsightsAccessPolicy, and returns the corresponding seriesInsightsAccessPolicy object, and an error if there is any.
func (c *FakeSeriesInsightsAccessPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SeriesInsightsAccessPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(seriesinsightsaccesspoliciesResource, c.ns, name), &v1alpha1.SeriesInsightsAccessPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SeriesInsightsAccessPolicy), err
}

// List takes label and field selectors, and returns the list of SeriesInsightsAccessPolicies that match those selectors.
func (c *FakeSeriesInsightsAccessPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SeriesInsightsAccessPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(seriesinsightsaccesspoliciesResource, seriesinsightsaccesspoliciesKind, c.ns, opts), &v1alpha1.SeriesInsightsAccessPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SeriesInsightsAccessPolicyList{ListMeta: obj.(*v1alpha1.SeriesInsightsAccessPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.SeriesInsightsAccessPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested seriesInsightsAccessPolicies.
func (c *FakeSeriesInsightsAccessPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(seriesinsightsaccesspoliciesResource, c.ns, opts))

}

// Create takes the representation of a seriesInsightsAccessPolicy and creates it.  Returns the server's representation of the seriesInsightsAccessPolicy, and an error, if there is any.
func (c *FakeSeriesInsightsAccessPolicies) Create(ctx context.Context, seriesInsightsAccessPolicy *v1alpha1.SeriesInsightsAccessPolicy, opts v1.CreateOptions) (result *v1alpha1.SeriesInsightsAccessPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(seriesinsightsaccesspoliciesResource, c.ns, seriesInsightsAccessPolicy), &v1alpha1.SeriesInsightsAccessPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SeriesInsightsAccessPolicy), err
}

// Update takes the representation of a seriesInsightsAccessPolicy and updates it. Returns the server's representation of the seriesInsightsAccessPolicy, and an error, if there is any.
func (c *FakeSeriesInsightsAccessPolicies) Update(ctx context.Context, seriesInsightsAccessPolicy *v1alpha1.SeriesInsightsAccessPolicy, opts v1.UpdateOptions) (result *v1alpha1.SeriesInsightsAccessPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(seriesinsightsaccesspoliciesResource, c.ns, seriesInsightsAccessPolicy), &v1alpha1.SeriesInsightsAccessPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SeriesInsightsAccessPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSeriesInsightsAccessPolicies) UpdateStatus(ctx context.Context, seriesInsightsAccessPolicy *v1alpha1.SeriesInsightsAccessPolicy, opts v1.UpdateOptions) (*v1alpha1.SeriesInsightsAccessPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(seriesinsightsaccesspoliciesResource, "status", c.ns, seriesInsightsAccessPolicy), &v1alpha1.SeriesInsightsAccessPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SeriesInsightsAccessPolicy), err
}

// Delete takes name of the seriesInsightsAccessPolicy and deletes it. Returns an error if one occurs.
func (c *FakeSeriesInsightsAccessPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(seriesinsightsaccesspoliciesResource, c.ns, name), &v1alpha1.SeriesInsightsAccessPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSeriesInsightsAccessPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(seriesinsightsaccesspoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SeriesInsightsAccessPolicyList{})
	return err
}

// Patch applies the patch and returns the patched seriesInsightsAccessPolicy.
func (c *FakeSeriesInsightsAccessPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SeriesInsightsAccessPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(seriesinsightsaccesspoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.SeriesInsightsAccessPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SeriesInsightsAccessPolicy), err
}
