/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/data/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProtectionBackupVaults implements ProtectionBackupVaultInterface
type FakeProtectionBackupVaults struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var protectionbackupvaultsResource = schema.GroupVersionResource{Group: "data.azurerm.kubeform.com", Version: "v1alpha1", Resource: "protectionbackupvaults"}

var protectionbackupvaultsKind = schema.GroupVersionKind{Group: "data.azurerm.kubeform.com", Version: "v1alpha1", Kind: "ProtectionBackupVault"}

// Get takes name of the protectionBackupVault, and returns the corresponding protectionBackupVault object, and an error if there is any.
func (c *FakeProtectionBackupVaults) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProtectionBackupVault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(protectionbackupvaultsResource, c.ns, name), &v1alpha1.ProtectionBackupVault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectionBackupVault), err
}

// List takes label and field selectors, and returns the list of ProtectionBackupVaults that match those selectors.
func (c *FakeProtectionBackupVaults) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProtectionBackupVaultList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(protectionbackupvaultsResource, protectionbackupvaultsKind, c.ns, opts), &v1alpha1.ProtectionBackupVaultList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProtectionBackupVaultList{ListMeta: obj.(*v1alpha1.ProtectionBackupVaultList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProtectionBackupVaultList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested protectionBackupVaults.
func (c *FakeProtectionBackupVaults) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(protectionbackupvaultsResource, c.ns, opts))

}

// Create takes the representation of a protectionBackupVault and creates it.  Returns the server's representation of the protectionBackupVault, and an error, if there is any.
func (c *FakeProtectionBackupVaults) Create(ctx context.Context, protectionBackupVault *v1alpha1.ProtectionBackupVault, opts v1.CreateOptions) (result *v1alpha1.ProtectionBackupVault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(protectionbackupvaultsResource, c.ns, protectionBackupVault), &v1alpha1.ProtectionBackupVault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectionBackupVault), err
}

// Update takes the representation of a protectionBackupVault and updates it. Returns the server's representation of the protectionBackupVault, and an error, if there is any.
func (c *FakeProtectionBackupVaults) Update(ctx context.Context, protectionBackupVault *v1alpha1.ProtectionBackupVault, opts v1.UpdateOptions) (result *v1alpha1.ProtectionBackupVault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(protectionbackupvaultsResource, c.ns, protectionBackupVault), &v1alpha1.ProtectionBackupVault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectionBackupVault), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProtectionBackupVaults) UpdateStatus(ctx context.Context, protectionBackupVault *v1alpha1.ProtectionBackupVault, opts v1.UpdateOptions) (*v1alpha1.ProtectionBackupVault, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(protectionbackupvaultsResource, "status", c.ns, protectionBackupVault), &v1alpha1.ProtectionBackupVault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectionBackupVault), err
}

// Delete takes name of the protectionBackupVault and deletes it. Returns an error if one occurs.
func (c *FakeProtectionBackupVaults) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(protectionbackupvaultsResource, c.ns, name), &v1alpha1.ProtectionBackupVault{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProtectionBackupVaults) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(protectionbackupvaultsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProtectionBackupVaultList{})
	return err
}

// Patch applies the patch and returns the patched protectionBackupVault.
func (c *FakeProtectionBackupVaults) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProtectionBackupVault, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(protectionbackupvaultsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProtectionBackupVault{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectionBackupVault), err
}
