/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/data/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeShareDatasetKustoClusters implements ShareDatasetKustoClusterInterface
type FakeShareDatasetKustoClusters struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var sharedatasetkustoclustersResource = schema.GroupVersionResource{Group: "data.azurerm.kubeform.com", Version: "v1alpha1", Resource: "sharedatasetkustoclusters"}

var sharedatasetkustoclustersKind = schema.GroupVersionKind{Group: "data.azurerm.kubeform.com", Version: "v1alpha1", Kind: "ShareDatasetKustoCluster"}

// Get takes name of the shareDatasetKustoCluster, and returns the corresponding shareDatasetKustoCluster object, and an error if there is any.
func (c *FakeShareDatasetKustoClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ShareDatasetKustoCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sharedatasetkustoclustersResource, c.ns, name), &v1alpha1.ShareDatasetKustoCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ShareDatasetKustoCluster), err
}

// List takes label and field selectors, and returns the list of ShareDatasetKustoClusters that match those selectors.
func (c *FakeShareDatasetKustoClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ShareDatasetKustoClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sharedatasetkustoclustersResource, sharedatasetkustoclustersKind, c.ns, opts), &v1alpha1.ShareDatasetKustoClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ShareDatasetKustoClusterList{ListMeta: obj.(*v1alpha1.ShareDatasetKustoClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.ShareDatasetKustoClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested shareDatasetKustoClusters.
func (c *FakeShareDatasetKustoClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sharedatasetkustoclustersResource, c.ns, opts))

}

// Create takes the representation of a shareDatasetKustoCluster and creates it.  Returns the server's representation of the shareDatasetKustoCluster, and an error, if there is any.
func (c *FakeShareDatasetKustoClusters) Create(ctx context.Context, shareDatasetKustoCluster *v1alpha1.ShareDatasetKustoCluster, opts v1.CreateOptions) (result *v1alpha1.ShareDatasetKustoCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sharedatasetkustoclustersResource, c.ns, shareDatasetKustoCluster), &v1alpha1.ShareDatasetKustoCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ShareDatasetKustoCluster), err
}

// Update takes the representation of a shareDatasetKustoCluster and updates it. Returns the server's representation of the shareDatasetKustoCluster, and an error, if there is any.
func (c *FakeShareDatasetKustoClusters) Update(ctx context.Context, shareDatasetKustoCluster *v1alpha1.ShareDatasetKustoCluster, opts v1.UpdateOptions) (result *v1alpha1.ShareDatasetKustoCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sharedatasetkustoclustersResource, c.ns, shareDatasetKustoCluster), &v1alpha1.ShareDatasetKustoCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ShareDatasetKustoCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeShareDatasetKustoClusters) UpdateStatus(ctx context.Context, shareDatasetKustoCluster *v1alpha1.ShareDatasetKustoCluster, opts v1.UpdateOptions) (*v1alpha1.ShareDatasetKustoCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sharedatasetkustoclustersResource, "status", c.ns, shareDatasetKustoCluster), &v1alpha1.ShareDatasetKustoCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ShareDatasetKustoCluster), err
}

// Delete takes name of the shareDatasetKustoCluster and deletes it. Returns an error if one occurs.
func (c *FakeShareDatasetKustoClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sharedatasetkustoclustersResource, c.ns, name), &v1alpha1.ShareDatasetKustoCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeShareDatasetKustoClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sharedatasetkustoclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ShareDatasetKustoClusterList{})
	return err
}

// Patch applies the patch and returns the patched shareDatasetKustoCluster.
func (c *FakeShareDatasetKustoClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ShareDatasetKustoCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sharedatasetkustoclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ShareDatasetKustoCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ShareDatasetKustoCluster), err
}
