/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/data/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProtectionBackupPolicyPostgresqls implements ProtectionBackupPolicyPostgresqlInterface
type FakeProtectionBackupPolicyPostgresqls struct {
	Fake *FakeDataV1alpha1
	ns   string
}

var protectionbackuppolicypostgresqlsResource = schema.GroupVersionResource{Group: "data.azurerm.kubeform.com", Version: "v1alpha1", Resource: "protectionbackuppolicypostgresqls"}

var protectionbackuppolicypostgresqlsKind = schema.GroupVersionKind{Group: "data.azurerm.kubeform.com", Version: "v1alpha1", Kind: "ProtectionBackupPolicyPostgresql"}

// Get takes name of the protectionBackupPolicyPostgresql, and returns the corresponding protectionBackupPolicyPostgresql object, and an error if there is any.
func (c *FakeProtectionBackupPolicyPostgresqls) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProtectionBackupPolicyPostgresql, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(protectionbackuppolicypostgresqlsResource, c.ns, name), &v1alpha1.ProtectionBackupPolicyPostgresql{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectionBackupPolicyPostgresql), err
}

// List takes label and field selectors, and returns the list of ProtectionBackupPolicyPostgresqls that match those selectors.
func (c *FakeProtectionBackupPolicyPostgresqls) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProtectionBackupPolicyPostgresqlList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(protectionbackuppolicypostgresqlsResource, protectionbackuppolicypostgresqlsKind, c.ns, opts), &v1alpha1.ProtectionBackupPolicyPostgresqlList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProtectionBackupPolicyPostgresqlList{ListMeta: obj.(*v1alpha1.ProtectionBackupPolicyPostgresqlList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProtectionBackupPolicyPostgresqlList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested protectionBackupPolicyPostgresqls.
func (c *FakeProtectionBackupPolicyPostgresqls) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(protectionbackuppolicypostgresqlsResource, c.ns, opts))

}

// Create takes the representation of a protectionBackupPolicyPostgresql and creates it.  Returns the server's representation of the protectionBackupPolicyPostgresql, and an error, if there is any.
func (c *FakeProtectionBackupPolicyPostgresqls) Create(ctx context.Context, protectionBackupPolicyPostgresql *v1alpha1.ProtectionBackupPolicyPostgresql, opts v1.CreateOptions) (result *v1alpha1.ProtectionBackupPolicyPostgresql, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(protectionbackuppolicypostgresqlsResource, c.ns, protectionBackupPolicyPostgresql), &v1alpha1.ProtectionBackupPolicyPostgresql{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectionBackupPolicyPostgresql), err
}

// Update takes the representation of a protectionBackupPolicyPostgresql and updates it. Returns the server's representation of the protectionBackupPolicyPostgresql, and an error, if there is any.
func (c *FakeProtectionBackupPolicyPostgresqls) Update(ctx context.Context, protectionBackupPolicyPostgresql *v1alpha1.ProtectionBackupPolicyPostgresql, opts v1.UpdateOptions) (result *v1alpha1.ProtectionBackupPolicyPostgresql, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(protectionbackuppolicypostgresqlsResource, c.ns, protectionBackupPolicyPostgresql), &v1alpha1.ProtectionBackupPolicyPostgresql{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectionBackupPolicyPostgresql), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProtectionBackupPolicyPostgresqls) UpdateStatus(ctx context.Context, protectionBackupPolicyPostgresql *v1alpha1.ProtectionBackupPolicyPostgresql, opts v1.UpdateOptions) (*v1alpha1.ProtectionBackupPolicyPostgresql, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(protectionbackuppolicypostgresqlsResource, "status", c.ns, protectionBackupPolicyPostgresql), &v1alpha1.ProtectionBackupPolicyPostgresql{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectionBackupPolicyPostgresql), err
}

// Delete takes name of the protectionBackupPolicyPostgresql and deletes it. Returns an error if one occurs.
func (c *FakeProtectionBackupPolicyPostgresqls) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(protectionbackuppolicypostgresqlsResource, c.ns, name), &v1alpha1.ProtectionBackupPolicyPostgresql{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProtectionBackupPolicyPostgresqls) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(protectionbackuppolicypostgresqlsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProtectionBackupPolicyPostgresqlList{})
	return err
}

// Patch applies the patch and returns the patched protectionBackupPolicyPostgresql.
func (c *FakeProtectionBackupPolicyPostgresqls) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProtectionBackupPolicyPostgresql, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(protectionbackuppolicypostgresqlsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProtectionBackupPolicyPostgresql{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProtectionBackupPolicyPostgresql), err
}
