/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// GatewayListerExpansion allows custom methods to be added to
// GatewayLister.
type GatewayListerExpansion interface{}

// GatewayNamespaceListerExpansion allows custom methods to be added to
// GatewayNamespaceLister.
type GatewayNamespaceListerExpansion interface{}

// InsightsListerExpansion allows custom methods to be added to
// InsightsLister.
type InsightsListerExpansion interface{}

// InsightsNamespaceListerExpansion allows custom methods to be added to
// InsightsNamespaceLister.
type InsightsNamespaceListerExpansion interface{}

// InsightsAPIKeyListerExpansion allows custom methods to be added to
// InsightsAPIKeyLister.
type InsightsAPIKeyListerExpansion interface{}

// InsightsAPIKeyNamespaceListerExpansion allows custom methods to be added to
// InsightsAPIKeyNamespaceLister.
type InsightsAPIKeyNamespaceListerExpansion interface{}

// InsightsAnalyticsItemListerExpansion allows custom methods to be added to
// InsightsAnalyticsItemLister.
type InsightsAnalyticsItemListerExpansion interface{}

// InsightsAnalyticsItemNamespaceListerExpansion allows custom methods to be added to
// InsightsAnalyticsItemNamespaceLister.
type InsightsAnalyticsItemNamespaceListerExpansion interface{}

// InsightsSmartDetectionRuleListerExpansion allows custom methods to be added to
// InsightsSmartDetectionRuleLister.
type InsightsSmartDetectionRuleListerExpansion interface{}

// InsightsSmartDetectionRuleNamespaceListerExpansion allows custom methods to be added to
// InsightsSmartDetectionRuleNamespaceLister.
type InsightsSmartDetectionRuleNamespaceListerExpansion interface{}

// InsightsWebtestListerExpansion allows custom methods to be added to
// InsightsWebtestLister.
type InsightsWebtestListerExpansion interface{}

// InsightsWebtestNamespaceListerExpansion allows custom methods to be added to
// InsightsWebtestNamespaceLister.
type InsightsWebtestNamespaceListerExpansion interface{}

// SecurityGroupListerExpansion allows custom methods to be added to
// SecurityGroupLister.
type SecurityGroupListerExpansion interface{}

// SecurityGroupNamespaceListerExpansion allows custom methods to be added to
// SecurityGroupNamespaceLister.
type SecurityGroupNamespaceListerExpansion interface{}
