/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/postgresql/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeActiveDirectoryAdministrators implements ActiveDirectoryAdministratorInterface
type FakeActiveDirectoryAdministrators struct {
	Fake *FakePostgresqlV1alpha1
	ns   string
}

var activedirectoryadministratorsResource = schema.GroupVersionResource{Group: "postgresql.azurerm.kubeform.com", Version: "v1alpha1", Resource: "activedirectoryadministrators"}

var activedirectoryadministratorsKind = schema.GroupVersionKind{Group: "postgresql.azurerm.kubeform.com", Version: "v1alpha1", Kind: "ActiveDirectoryAdministrator"}

// Get takes name of the activeDirectoryAdministrator, and returns the corresponding activeDirectoryAdministrator object, and an error if there is any.
func (c *FakeActiveDirectoryAdministrators) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ActiveDirectoryAdministrator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(activedirectoryadministratorsResource, c.ns, name), &v1alpha1.ActiveDirectoryAdministrator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiveDirectoryAdministrator), err
}

// List takes label and field selectors, and returns the list of ActiveDirectoryAdministrators that match those selectors.
func (c *FakeActiveDirectoryAdministrators) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ActiveDirectoryAdministratorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(activedirectoryadministratorsResource, activedirectoryadministratorsKind, c.ns, opts), &v1alpha1.ActiveDirectoryAdministratorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ActiveDirectoryAdministratorList{ListMeta: obj.(*v1alpha1.ActiveDirectoryAdministratorList).ListMeta}
	for _, item := range obj.(*v1alpha1.ActiveDirectoryAdministratorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested activeDirectoryAdministrators.
func (c *FakeActiveDirectoryAdministrators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(activedirectoryadministratorsResource, c.ns, opts))

}

// Create takes the representation of a activeDirectoryAdministrator and creates it.  Returns the server's representation of the activeDirectoryAdministrator, and an error, if there is any.
func (c *FakeActiveDirectoryAdministrators) Create(ctx context.Context, activeDirectoryAdministrator *v1alpha1.ActiveDirectoryAdministrator, opts v1.CreateOptions) (result *v1alpha1.ActiveDirectoryAdministrator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(activedirectoryadministratorsResource, c.ns, activeDirectoryAdministrator), &v1alpha1.ActiveDirectoryAdministrator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiveDirectoryAdministrator), err
}

// Update takes the representation of a activeDirectoryAdministrator and updates it. Returns the server's representation of the activeDirectoryAdministrator, and an error, if there is any.
func (c *FakeActiveDirectoryAdministrators) Update(ctx context.Context, activeDirectoryAdministrator *v1alpha1.ActiveDirectoryAdministrator, opts v1.UpdateOptions) (result *v1alpha1.ActiveDirectoryAdministrator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(activedirectoryadministratorsResource, c.ns, activeDirectoryAdministrator), &v1alpha1.ActiveDirectoryAdministrator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiveDirectoryAdministrator), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeActiveDirectoryAdministrators) UpdateStatus(ctx context.Context, activeDirectoryAdministrator *v1alpha1.ActiveDirectoryAdministrator, opts v1.UpdateOptions) (*v1alpha1.ActiveDirectoryAdministrator, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(activedirectoryadministratorsResource, "status", c.ns, activeDirectoryAdministrator), &v1alpha1.ActiveDirectoryAdministrator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiveDirectoryAdministrator), err
}

// Delete takes name of the activeDirectoryAdministrator and deletes it. Returns an error if one occurs.
func (c *FakeActiveDirectoryAdministrators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(activedirectoryadministratorsResource, c.ns, name), &v1alpha1.ActiveDirectoryAdministrator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeActiveDirectoryAdministrators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(activedirectoryadministratorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ActiveDirectoryAdministratorList{})
	return err
}

// Patch applies the patch and returns the patched activeDirectoryAdministrator.
func (c *FakeActiveDirectoryAdministrators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ActiveDirectoryAdministrator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(activedirectoryadministratorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ActiveDirectoryAdministrator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActiveDirectoryAdministrator), err
}
