/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/lb/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOutboundRules implements OutboundRuleInterface
type FakeOutboundRules struct {
	Fake *FakeLbV1alpha1
	ns   string
}

var outboundrulesResource = schema.GroupVersionResource{Group: "lb.azurerm.kubeform.com", Version: "v1alpha1", Resource: "outboundrules"}

var outboundrulesKind = schema.GroupVersionKind{Group: "lb.azurerm.kubeform.com", Version: "v1alpha1", Kind: "OutboundRule"}

// Get takes name of the outboundRule, and returns the corresponding outboundRule object, and an error if there is any.
func (c *FakeOutboundRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OutboundRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(outboundrulesResource, c.ns, name), &v1alpha1.OutboundRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OutboundRule), err
}

// List takes label and field selectors, and returns the list of OutboundRules that match those selectors.
func (c *FakeOutboundRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OutboundRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(outboundrulesResource, outboundrulesKind, c.ns, opts), &v1alpha1.OutboundRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OutboundRuleList{ListMeta: obj.(*v1alpha1.OutboundRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.OutboundRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested outboundRules.
func (c *FakeOutboundRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(outboundrulesResource, c.ns, opts))

}

// Create takes the representation of a outboundRule and creates it.  Returns the server's representation of the outboundRule, and an error, if there is any.
func (c *FakeOutboundRules) Create(ctx context.Context, outboundRule *v1alpha1.OutboundRule, opts v1.CreateOptions) (result *v1alpha1.OutboundRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(outboundrulesResource, c.ns, outboundRule), &v1alpha1.OutboundRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OutboundRule), err
}

// Update takes the representation of a outboundRule and updates it. Returns the server's representation of the outboundRule, and an error, if there is any.
func (c *FakeOutboundRules) Update(ctx context.Context, outboundRule *v1alpha1.OutboundRule, opts v1.UpdateOptions) (result *v1alpha1.OutboundRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(outboundrulesResource, c.ns, outboundRule), &v1alpha1.OutboundRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OutboundRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeOutboundRules) UpdateStatus(ctx context.Context, outboundRule *v1alpha1.OutboundRule, opts v1.UpdateOptions) (*v1alpha1.OutboundRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(outboundrulesResource, "status", c.ns, outboundRule), &v1alpha1.OutboundRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OutboundRule), err
}

// Delete takes name of the outboundRule and deletes it. Returns an error if one occurs.
func (c *FakeOutboundRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(outboundrulesResource, c.ns, name), &v1alpha1.OutboundRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOutboundRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(outboundrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OutboundRuleList{})
	return err
}

// Patch applies the patch and returns the patched outboundRule.
func (c *FakeOutboundRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OutboundRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(outboundrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.OutboundRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.OutboundRule), err
}
