/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/relay/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHybridConnections implements HybridConnectionInterface
type FakeHybridConnections struct {
	Fake *FakeRelayV1alpha1
	ns   string
}

var hybridconnectionsResource = schema.GroupVersionResource{Group: "relay.azurerm.kubeform.com", Version: "v1alpha1", Resource: "hybridconnections"}

var hybridconnectionsKind = schema.GroupVersionKind{Group: "relay.azurerm.kubeform.com", Version: "v1alpha1", Kind: "HybridConnection"}

// Get takes name of the hybridConnection, and returns the corresponding hybridConnection object, and an error if there is any.
func (c *FakeHybridConnections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HybridConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hybridconnectionsResource, c.ns, name), &v1alpha1.HybridConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HybridConnection), err
}

// List takes label and field selectors, and returns the list of HybridConnections that match those selectors.
func (c *FakeHybridConnections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HybridConnectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hybridconnectionsResource, hybridconnectionsKind, c.ns, opts), &v1alpha1.HybridConnectionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HybridConnectionList{ListMeta: obj.(*v1alpha1.HybridConnectionList).ListMeta}
	for _, item := range obj.(*v1alpha1.HybridConnectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hybridConnections.
func (c *FakeHybridConnections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hybridconnectionsResource, c.ns, opts))

}

// Create takes the representation of a hybridConnection and creates it.  Returns the server's representation of the hybridConnection, and an error, if there is any.
func (c *FakeHybridConnections) Create(ctx context.Context, hybridConnection *v1alpha1.HybridConnection, opts v1.CreateOptions) (result *v1alpha1.HybridConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hybridconnectionsResource, c.ns, hybridConnection), &v1alpha1.HybridConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HybridConnection), err
}

// Update takes the representation of a hybridConnection and updates it. Returns the server's representation of the hybridConnection, and an error, if there is any.
func (c *FakeHybridConnections) Update(ctx context.Context, hybridConnection *v1alpha1.HybridConnection, opts v1.UpdateOptions) (result *v1alpha1.HybridConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hybridconnectionsResource, c.ns, hybridConnection), &v1alpha1.HybridConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HybridConnection), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHybridConnections) UpdateStatus(ctx context.Context, hybridConnection *v1alpha1.HybridConnection, opts v1.UpdateOptions) (*v1alpha1.HybridConnection, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hybridconnectionsResource, "status", c.ns, hybridConnection), &v1alpha1.HybridConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HybridConnection), err
}

// Delete takes name of the hybridConnection and deletes it. Returns an error if one occurs.
func (c *FakeHybridConnections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hybridconnectionsResource, c.ns, name), &v1alpha1.HybridConnection{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHybridConnections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hybridconnectionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HybridConnectionList{})
	return err
}

// Patch applies the patch and returns the patched hybridConnection.
func (c *FakeHybridConnections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HybridConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hybridconnectionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.HybridConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HybridConnection), err
}
