/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/iothub/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEnrichments implements EnrichmentInterface
type FakeEnrichments struct {
	Fake *FakeIothubV1alpha1
	ns   string
}

var enrichmentsResource = schema.GroupVersionResource{Group: "iothub.azurerm.kubeform.com", Version: "v1alpha1", Resource: "enrichments"}

var enrichmentsKind = schema.GroupVersionKind{Group: "iothub.azurerm.kubeform.com", Version: "v1alpha1", Kind: "Enrichment"}

// Get takes name of the enrichment, and returns the corresponding enrichment object, and an error if there is any.
func (c *FakeEnrichments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Enrichment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(enrichmentsResource, c.ns, name), &v1alpha1.Enrichment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Enrichment), err
}

// List takes label and field selectors, and returns the list of Enrichments that match those selectors.
func (c *FakeEnrichments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EnrichmentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(enrichmentsResource, enrichmentsKind, c.ns, opts), &v1alpha1.EnrichmentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EnrichmentList{ListMeta: obj.(*v1alpha1.EnrichmentList).ListMeta}
	for _, item := range obj.(*v1alpha1.EnrichmentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested enrichments.
func (c *FakeEnrichments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(enrichmentsResource, c.ns, opts))

}

// Create takes the representation of a enrichment and creates it.  Returns the server's representation of the enrichment, and an error, if there is any.
func (c *FakeEnrichments) Create(ctx context.Context, enrichment *v1alpha1.Enrichment, opts v1.CreateOptions) (result *v1alpha1.Enrichment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(enrichmentsResource, c.ns, enrichment), &v1alpha1.Enrichment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Enrichment), err
}

// Update takes the representation of a enrichment and updates it. Returns the server's representation of the enrichment, and an error, if there is any.
func (c *FakeEnrichments) Update(ctx context.Context, enrichment *v1alpha1.Enrichment, opts v1.UpdateOptions) (result *v1alpha1.Enrichment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(enrichmentsResource, c.ns, enrichment), &v1alpha1.Enrichment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Enrichment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEnrichments) UpdateStatus(ctx context.Context, enrichment *v1alpha1.Enrichment, opts v1.UpdateOptions) (*v1alpha1.Enrichment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(enrichmentsResource, "status", c.ns, enrichment), &v1alpha1.Enrichment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Enrichment), err
}

// Delete takes name of the enrichment and deletes it. Returns an error if one occurs.
func (c *FakeEnrichments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(enrichmentsResource, c.ns, name), &v1alpha1.Enrichment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEnrichments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(enrichmentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EnrichmentList{})
	return err
}

// Patch applies the patch and returns the patched enrichment.
func (c *FakeEnrichments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Enrichment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(enrichmentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Enrichment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Enrichment), err
}
