/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/iothub/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFallbackRoutes implements FallbackRouteInterface
type FakeFallbackRoutes struct {
	Fake *FakeIothubV1alpha1
	ns   string
}

var fallbackroutesResource = schema.GroupVersionResource{Group: "iothub.azurerm.kubeform.com", Version: "v1alpha1", Resource: "fallbackroutes"}

var fallbackroutesKind = schema.GroupVersionKind{Group: "iothub.azurerm.kubeform.com", Version: "v1alpha1", Kind: "FallbackRoute"}

// Get takes name of the fallbackRoute, and returns the corresponding fallbackRoute object, and an error if there is any.
func (c *FakeFallbackRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.FallbackRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(fallbackroutesResource, c.ns, name), &v1alpha1.FallbackRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FallbackRoute), err
}

// List takes label and field selectors, and returns the list of FallbackRoutes that match those selectors.
func (c *FakeFallbackRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FallbackRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(fallbackroutesResource, fallbackroutesKind, c.ns, opts), &v1alpha1.FallbackRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FallbackRouteList{ListMeta: obj.(*v1alpha1.FallbackRouteList).ListMeta}
	for _, item := range obj.(*v1alpha1.FallbackRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fallbackRoutes.
func (c *FakeFallbackRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(fallbackroutesResource, c.ns, opts))

}

// Create takes the representation of a fallbackRoute and creates it.  Returns the server's representation of the fallbackRoute, and an error, if there is any.
func (c *FakeFallbackRoutes) Create(ctx context.Context, fallbackRoute *v1alpha1.FallbackRoute, opts v1.CreateOptions) (result *v1alpha1.FallbackRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(fallbackroutesResource, c.ns, fallbackRoute), &v1alpha1.FallbackRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FallbackRoute), err
}

// Update takes the representation of a fallbackRoute and updates it. Returns the server's representation of the fallbackRoute, and an error, if there is any.
func (c *FakeFallbackRoutes) Update(ctx context.Context, fallbackRoute *v1alpha1.FallbackRoute, opts v1.UpdateOptions) (result *v1alpha1.FallbackRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(fallbackroutesResource, c.ns, fallbackRoute), &v1alpha1.FallbackRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FallbackRoute), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFallbackRoutes) UpdateStatus(ctx context.Context, fallbackRoute *v1alpha1.FallbackRoute, opts v1.UpdateOptions) (*v1alpha1.FallbackRoute, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(fallbackroutesResource, "status", c.ns, fallbackRoute), &v1alpha1.FallbackRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FallbackRoute), err
}

// Delete takes name of the fallbackRoute and deletes it. Returns an error if one occurs.
func (c *FakeFallbackRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(fallbackroutesResource, c.ns, name), &v1alpha1.FallbackRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFallbackRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(fallbackroutesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FallbackRouteList{})
	return err
}

// Patch applies the patch and returns the patched fallbackRoute.
func (c *FakeFallbackRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.FallbackRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(fallbackroutesResource, c.ns, name, pt, data, subresources...), &v1alpha1.FallbackRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.FallbackRoute), err
}
