/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/load/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLoadtests implements LoadtestInterface
type FakeLoadtests struct {
	Fake *FakeLoadV1alpha1
	ns   string
}

var loadtestsResource = schema.GroupVersionResource{Group: "load.azurerm.kubeform.com", Version: "v1alpha1", Resource: "loadtests"}

var loadtestsKind = schema.GroupVersionKind{Group: "load.azurerm.kubeform.com", Version: "v1alpha1", Kind: "Loadtest"}

// Get takes name of the loadtest, and returns the corresponding loadtest object, and an error if there is any.
func (c *FakeLoadtests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Loadtest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(loadtestsResource, c.ns, name), &v1alpha1.Loadtest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Loadtest), err
}

// List takes label and field selectors, and returns the list of Loadtests that match those selectors.
func (c *FakeLoadtests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LoadtestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(loadtestsResource, loadtestsKind, c.ns, opts), &v1alpha1.LoadtestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LoadtestList{ListMeta: obj.(*v1alpha1.LoadtestList).ListMeta}
	for _, item := range obj.(*v1alpha1.LoadtestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested loadtests.
func (c *FakeLoadtests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(loadtestsResource, c.ns, opts))

}

// Create takes the representation of a loadtest and creates it.  Returns the server's representation of the loadtest, and an error, if there is any.
func (c *FakeLoadtests) Create(ctx context.Context, loadtest *v1alpha1.Loadtest, opts v1.CreateOptions) (result *v1alpha1.Loadtest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(loadtestsResource, c.ns, loadtest), &v1alpha1.Loadtest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Loadtest), err
}

// Update takes the representation of a loadtest and updates it. Returns the server's representation of the loadtest, and an error, if there is any.
func (c *FakeLoadtests) Update(ctx context.Context, loadtest *v1alpha1.Loadtest, opts v1.UpdateOptions) (result *v1alpha1.Loadtest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(loadtestsResource, c.ns, loadtest), &v1alpha1.Loadtest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Loadtest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLoadtests) UpdateStatus(ctx context.Context, loadtest *v1alpha1.Loadtest, opts v1.UpdateOptions) (*v1alpha1.Loadtest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(loadtestsResource, "status", c.ns, loadtest), &v1alpha1.Loadtest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Loadtest), err
}

// Delete takes name of the loadtest and deletes it. Returns an error if one occurs.
func (c *FakeLoadtests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(loadtestsResource, c.ns, name), &v1alpha1.Loadtest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLoadtests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(loadtestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LoadtestList{})
	return err
}

// Patch applies the patch and returns the patched loadtest.
func (c *FakeLoadtests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Loadtest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(loadtestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Loadtest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Loadtest), err
}
