/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	expressroutev1alpha1 "kubeform.dev/provider-azurerm-api/apis/expressroute/v1alpha1"
	versioned "kubeform.dev/provider-azurerm-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-azurerm-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-azurerm-api/client/listers/expressroute/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CircuitPeeringInformer provides access to a shared informer and lister for
// CircuitPeerings.
type CircuitPeeringInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.CircuitPeeringLister
}

type circuitPeeringInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCircuitPeeringInformer constructs a new informer for CircuitPeering type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCircuitPeeringInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCircuitPeeringInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCircuitPeeringInformer constructs a new informer for CircuitPeering type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCircuitPeeringInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExpressrouteV1alpha1().CircuitPeerings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExpressrouteV1alpha1().CircuitPeerings(namespace).Watch(context.TODO(), options)
			},
		},
		&expressroutev1alpha1.CircuitPeering{},
		resyncPeriod,
		indexers,
	)
}

func (f *circuitPeeringInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCircuitPeeringInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *circuitPeeringInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&expressroutev1alpha1.CircuitPeering{}, f.defaultInformer)
}

func (f *circuitPeeringInformer) Lister() v1alpha1.CircuitPeeringLister {
	return v1alpha1.NewCircuitPeeringLister(f.Informer().GetIndexer())
}
