/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/maintenance/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAssignmentDedicatedHosts implements AssignmentDedicatedHostInterface
type FakeAssignmentDedicatedHosts struct {
	Fake *FakeMaintenanceV1alpha1
	ns   string
}

var assignmentdedicatedhostsResource = schema.GroupVersionResource{Group: "maintenance.azurerm.kubeform.com", Version: "v1alpha1", Resource: "assignmentdedicatedhosts"}

var assignmentdedicatedhostsKind = schema.GroupVersionKind{Group: "maintenance.azurerm.kubeform.com", Version: "v1alpha1", Kind: "AssignmentDedicatedHost"}

// Get takes name of the assignmentDedicatedHost, and returns the corresponding assignmentDedicatedHost object, and an error if there is any.
func (c *FakeAssignmentDedicatedHosts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AssignmentDedicatedHost, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(assignmentdedicatedhostsResource, c.ns, name), &v1alpha1.AssignmentDedicatedHost{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AssignmentDedicatedHost), err
}

// List takes label and field selectors, and returns the list of AssignmentDedicatedHosts that match those selectors.
func (c *FakeAssignmentDedicatedHosts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AssignmentDedicatedHostList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(assignmentdedicatedhostsResource, assignmentdedicatedhostsKind, c.ns, opts), &v1alpha1.AssignmentDedicatedHostList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AssignmentDedicatedHostList{ListMeta: obj.(*v1alpha1.AssignmentDedicatedHostList).ListMeta}
	for _, item := range obj.(*v1alpha1.AssignmentDedicatedHostList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested assignmentDedicatedHosts.
func (c *FakeAssignmentDedicatedHosts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(assignmentdedicatedhostsResource, c.ns, opts))

}

// Create takes the representation of a assignmentDedicatedHost and creates it.  Returns the server's representation of the assignmentDedicatedHost, and an error, if there is any.
func (c *FakeAssignmentDedicatedHosts) Create(ctx context.Context, assignmentDedicatedHost *v1alpha1.AssignmentDedicatedHost, opts v1.CreateOptions) (result *v1alpha1.AssignmentDedicatedHost, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(assignmentdedicatedhostsResource, c.ns, assignmentDedicatedHost), &v1alpha1.AssignmentDedicatedHost{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AssignmentDedicatedHost), err
}

// Update takes the representation of a assignmentDedicatedHost and updates it. Returns the server's representation of the assignmentDedicatedHost, and an error, if there is any.
func (c *FakeAssignmentDedicatedHosts) Update(ctx context.Context, assignmentDedicatedHost *v1alpha1.AssignmentDedicatedHost, opts v1.UpdateOptions) (result *v1alpha1.AssignmentDedicatedHost, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(assignmentdedicatedhostsResource, c.ns, assignmentDedicatedHost), &v1alpha1.AssignmentDedicatedHost{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AssignmentDedicatedHost), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAssignmentDedicatedHosts) UpdateStatus(ctx context.Context, assignmentDedicatedHost *v1alpha1.AssignmentDedicatedHost, opts v1.UpdateOptions) (*v1alpha1.AssignmentDedicatedHost, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(assignmentdedicatedhostsResource, "status", c.ns, assignmentDedicatedHost), &v1alpha1.AssignmentDedicatedHost{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AssignmentDedicatedHost), err
}

// Delete takes name of the assignmentDedicatedHost and deletes it. Returns an error if one occurs.
func (c *FakeAssignmentDedicatedHosts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(assignmentdedicatedhostsResource, c.ns, name), &v1alpha1.AssignmentDedicatedHost{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAssignmentDedicatedHosts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(assignmentdedicatedhostsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AssignmentDedicatedHostList{})
	return err
}

// Patch applies the patch and returns the patched assignmentDedicatedHost.
func (c *FakeAssignmentDedicatedHosts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AssignmentDedicatedHost, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(assignmentdedicatedhostsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AssignmentDedicatedHost{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AssignmentDedicatedHost), err
}
