/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ActionCustomListerExpansion allows custom methods to be added to
// ActionCustomLister.
type ActionCustomListerExpansion interface{}

// ActionCustomNamespaceListerExpansion allows custom methods to be added to
// ActionCustomNamespaceLister.
type ActionCustomNamespaceListerExpansion interface{}

// ActionHTTPListerExpansion allows custom methods to be added to
// ActionHTTPLister.
type ActionHTTPListerExpansion interface{}

// ActionHTTPNamespaceListerExpansion allows custom methods to be added to
// ActionHTTPNamespaceLister.
type ActionHTTPNamespaceListerExpansion interface{}

// IntegrationAccountListerExpansion allows custom methods to be added to
// IntegrationAccountLister.
type IntegrationAccountListerExpansion interface{}

// IntegrationAccountNamespaceListerExpansion allows custom methods to be added to
// IntegrationAccountNamespaceLister.
type IntegrationAccountNamespaceListerExpansion interface{}

// TriggerCustomListerExpansion allows custom methods to be added to
// TriggerCustomLister.
type TriggerCustomListerExpansion interface{}

// TriggerCustomNamespaceListerExpansion allows custom methods to be added to
// TriggerCustomNamespaceLister.
type TriggerCustomNamespaceListerExpansion interface{}

// TriggerHTTPRequestListerExpansion allows custom methods to be added to
// TriggerHTTPRequestLister.
type TriggerHTTPRequestListerExpansion interface{}

// TriggerHTTPRequestNamespaceListerExpansion allows custom methods to be added to
// TriggerHTTPRequestNamespaceLister.
type TriggerHTTPRequestNamespaceListerExpansion interface{}

// TriggerRecurrenceListerExpansion allows custom methods to be added to
// TriggerRecurrenceLister.
type TriggerRecurrenceListerExpansion interface{}

// TriggerRecurrenceNamespaceListerExpansion allows custom methods to be added to
// TriggerRecurrenceNamespaceLister.
type TriggerRecurrenceNamespaceListerExpansion interface{}

// WorkflowListerExpansion allows custom methods to be added to
// WorkflowLister.
type WorkflowListerExpansion interface{}

// WorkflowNamespaceListerExpansion allows custom methods to be added to
// WorkflowNamespaceLister.
type WorkflowNamespaceListerExpansion interface{}
