/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/devtest/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLinuxVirtualMachines implements LinuxVirtualMachineInterface
type FakeLinuxVirtualMachines struct {
	Fake *FakeDevtestV1alpha1
	ns   string
}

var linuxvirtualmachinesResource = schema.GroupVersionResource{Group: "devtest.azurerm.kubeform.com", Version: "v1alpha1", Resource: "linuxvirtualmachines"}

var linuxvirtualmachinesKind = schema.GroupVersionKind{Group: "devtest.azurerm.kubeform.com", Version: "v1alpha1", Kind: "LinuxVirtualMachine"}

// Get takes name of the linuxVirtualMachine, and returns the corresponding linuxVirtualMachine object, and an error if there is any.
func (c *FakeLinuxVirtualMachines) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LinuxVirtualMachine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(linuxvirtualmachinesResource, c.ns, name), &v1alpha1.LinuxVirtualMachine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LinuxVirtualMachine), err
}

// List takes label and field selectors, and returns the list of LinuxVirtualMachines that match those selectors.
func (c *FakeLinuxVirtualMachines) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LinuxVirtualMachineList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(linuxvirtualmachinesResource, linuxvirtualmachinesKind, c.ns, opts), &v1alpha1.LinuxVirtualMachineList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LinuxVirtualMachineList{ListMeta: obj.(*v1alpha1.LinuxVirtualMachineList).ListMeta}
	for _, item := range obj.(*v1alpha1.LinuxVirtualMachineList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested linuxVirtualMachines.
func (c *FakeLinuxVirtualMachines) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(linuxvirtualmachinesResource, c.ns, opts))

}

// Create takes the representation of a linuxVirtualMachine and creates it.  Returns the server's representation of the linuxVirtualMachine, and an error, if there is any.
func (c *FakeLinuxVirtualMachines) Create(ctx context.Context, linuxVirtualMachine *v1alpha1.LinuxVirtualMachine, opts v1.CreateOptions) (result *v1alpha1.LinuxVirtualMachine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(linuxvirtualmachinesResource, c.ns, linuxVirtualMachine), &v1alpha1.LinuxVirtualMachine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LinuxVirtualMachine), err
}

// Update takes the representation of a linuxVirtualMachine and updates it. Returns the server's representation of the linuxVirtualMachine, and an error, if there is any.
func (c *FakeLinuxVirtualMachines) Update(ctx context.Context, linuxVirtualMachine *v1alpha1.LinuxVirtualMachine, opts v1.UpdateOptions) (result *v1alpha1.LinuxVirtualMachine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(linuxvirtualmachinesResource, c.ns, linuxVirtualMachine), &v1alpha1.LinuxVirtualMachine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LinuxVirtualMachine), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLinuxVirtualMachines) UpdateStatus(ctx context.Context, linuxVirtualMachine *v1alpha1.LinuxVirtualMachine, opts v1.UpdateOptions) (*v1alpha1.LinuxVirtualMachine, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(linuxvirtualmachinesResource, "status", c.ns, linuxVirtualMachine), &v1alpha1.LinuxVirtualMachine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LinuxVirtualMachine), err
}

// Delete takes name of the linuxVirtualMachine and deletes it. Returns an error if one occurs.
func (c *FakeLinuxVirtualMachines) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(linuxvirtualmachinesResource, c.ns, name), &v1alpha1.LinuxVirtualMachine{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLinuxVirtualMachines) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(linuxvirtualmachinesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LinuxVirtualMachineList{})
	return err
}

// Patch applies the patch and returns the patched linuxVirtualMachine.
func (c *FakeLinuxVirtualMachines) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LinuxVirtualMachine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(linuxvirtualmachinesResource, c.ns, name, pt, data, subresources...), &v1alpha1.LinuxVirtualMachine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LinuxVirtualMachine), err
}
