/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/devtest/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGlobalVmShutdownSchedules implements GlobalVmShutdownScheduleInterface
type FakeGlobalVmShutdownSchedules struct {
	Fake *FakeDevtestV1alpha1
	ns   string
}

var globalvmshutdownschedulesResource = schema.GroupVersionResource{Group: "devtest.azurerm.kubeform.com", Version: "v1alpha1", Resource: "globalvmshutdownschedules"}

var globalvmshutdownschedulesKind = schema.GroupVersionKind{Group: "devtest.azurerm.kubeform.com", Version: "v1alpha1", Kind: "GlobalVmShutdownSchedule"}

// Get takes name of the globalVmShutdownSchedule, and returns the corresponding globalVmShutdownSchedule object, and an error if there is any.
func (c *FakeGlobalVmShutdownSchedules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GlobalVmShutdownSchedule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(globalvmshutdownschedulesResource, c.ns, name), &v1alpha1.GlobalVmShutdownSchedule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalVmShutdownSchedule), err
}

// List takes label and field selectors, and returns the list of GlobalVmShutdownSchedules that match those selectors.
func (c *FakeGlobalVmShutdownSchedules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GlobalVmShutdownScheduleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(globalvmshutdownschedulesResource, globalvmshutdownschedulesKind, c.ns, opts), &v1alpha1.GlobalVmShutdownScheduleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GlobalVmShutdownScheduleList{ListMeta: obj.(*v1alpha1.GlobalVmShutdownScheduleList).ListMeta}
	for _, item := range obj.(*v1alpha1.GlobalVmShutdownScheduleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested globalVmShutdownSchedules.
func (c *FakeGlobalVmShutdownSchedules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(globalvmshutdownschedulesResource, c.ns, opts))

}

// Create takes the representation of a globalVmShutdownSchedule and creates it.  Returns the server's representation of the globalVmShutdownSchedule, and an error, if there is any.
func (c *FakeGlobalVmShutdownSchedules) Create(ctx context.Context, globalVmShutdownSchedule *v1alpha1.GlobalVmShutdownSchedule, opts v1.CreateOptions) (result *v1alpha1.GlobalVmShutdownSchedule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(globalvmshutdownschedulesResource, c.ns, globalVmShutdownSchedule), &v1alpha1.GlobalVmShutdownSchedule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalVmShutdownSchedule), err
}

// Update takes the representation of a globalVmShutdownSchedule and updates it. Returns the server's representation of the globalVmShutdownSchedule, and an error, if there is any.
func (c *FakeGlobalVmShutdownSchedules) Update(ctx context.Context, globalVmShutdownSchedule *v1alpha1.GlobalVmShutdownSchedule, opts v1.UpdateOptions) (result *v1alpha1.GlobalVmShutdownSchedule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(globalvmshutdownschedulesResource, c.ns, globalVmShutdownSchedule), &v1alpha1.GlobalVmShutdownSchedule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalVmShutdownSchedule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGlobalVmShutdownSchedules) UpdateStatus(ctx context.Context, globalVmShutdownSchedule *v1alpha1.GlobalVmShutdownSchedule, opts v1.UpdateOptions) (*v1alpha1.GlobalVmShutdownSchedule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(globalvmshutdownschedulesResource, "status", c.ns, globalVmShutdownSchedule), &v1alpha1.GlobalVmShutdownSchedule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalVmShutdownSchedule), err
}

// Delete takes name of the globalVmShutdownSchedule and deletes it. Returns an error if one occurs.
func (c *FakeGlobalVmShutdownSchedules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(globalvmshutdownschedulesResource, c.ns, name), &v1alpha1.GlobalVmShutdownSchedule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGlobalVmShutdownSchedules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(globalvmshutdownschedulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GlobalVmShutdownScheduleList{})
	return err
}

// Patch applies the patch and returns the patched globalVmShutdownSchedule.
func (c *FakeGlobalVmShutdownSchedules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalVmShutdownSchedule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(globalvmshutdownschedulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.GlobalVmShutdownSchedule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GlobalVmShutdownSchedule), err
}
