/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ConnectionMonitorListerExpansion allows custom methods to be added to
// ConnectionMonitorLister.
type ConnectionMonitorListerExpansion interface{}

// ConnectionMonitorNamespaceListerExpansion allows custom methods to be added to
// ConnectionMonitorNamespaceLister.
type ConnectionMonitorNamespaceListerExpansion interface{}

// DdosProtectionPlanListerExpansion allows custom methods to be added to
// DdosProtectionPlanLister.
type DdosProtectionPlanListerExpansion interface{}

// DdosProtectionPlanNamespaceListerExpansion allows custom methods to be added to
// DdosProtectionPlanNamespaceLister.
type DdosProtectionPlanNamespaceListerExpansion interface{}

// InterfaceListerExpansion allows custom methods to be added to
// InterfaceLister.
type InterfaceListerExpansion interface{}

// InterfaceNamespaceListerExpansion allows custom methods to be added to
// InterfaceNamespaceLister.
type InterfaceNamespaceListerExpansion interface{}

// InterfaceApplicationGatewayBackendAddressPoolAssociationListerExpansion allows custom methods to be added to
// InterfaceApplicationGatewayBackendAddressPoolAssociationLister.
type InterfaceApplicationGatewayBackendAddressPoolAssociationListerExpansion interface{}

// InterfaceApplicationGatewayBackendAddressPoolAssociationNamespaceListerExpansion allows custom methods to be added to
// InterfaceApplicationGatewayBackendAddressPoolAssociationNamespaceLister.
type InterfaceApplicationGatewayBackendAddressPoolAssociationNamespaceListerExpansion interface{}

// InterfaceApplicationSecurityGroupAssociationListerExpansion allows custom methods to be added to
// InterfaceApplicationSecurityGroupAssociationLister.
type InterfaceApplicationSecurityGroupAssociationListerExpansion interface{}

// InterfaceApplicationSecurityGroupAssociationNamespaceListerExpansion allows custom methods to be added to
// InterfaceApplicationSecurityGroupAssociationNamespaceLister.
type InterfaceApplicationSecurityGroupAssociationNamespaceListerExpansion interface{}

// InterfaceBackendAddressPoolAssociationListerExpansion allows custom methods to be added to
// InterfaceBackendAddressPoolAssociationLister.
type InterfaceBackendAddressPoolAssociationListerExpansion interface{}

// InterfaceBackendAddressPoolAssociationNamespaceListerExpansion allows custom methods to be added to
// InterfaceBackendAddressPoolAssociationNamespaceLister.
type InterfaceBackendAddressPoolAssociationNamespaceListerExpansion interface{}

// InterfaceNATRuleAssociationListerExpansion allows custom methods to be added to
// InterfaceNATRuleAssociationLister.
type InterfaceNATRuleAssociationListerExpansion interface{}

// InterfaceNATRuleAssociationNamespaceListerExpansion allows custom methods to be added to
// InterfaceNATRuleAssociationNamespaceLister.
type InterfaceNATRuleAssociationNamespaceListerExpansion interface{}

// InterfaceSecurityGroupAssociationListerExpansion allows custom methods to be added to
// InterfaceSecurityGroupAssociationLister.
type InterfaceSecurityGroupAssociationListerExpansion interface{}

// InterfaceSecurityGroupAssociationNamespaceListerExpansion allows custom methods to be added to
// InterfaceSecurityGroupAssociationNamespaceLister.
type InterfaceSecurityGroupAssociationNamespaceListerExpansion interface{}

// PacketCaptureListerExpansion allows custom methods to be added to
// PacketCaptureLister.
type PacketCaptureListerExpansion interface{}

// PacketCaptureNamespaceListerExpansion allows custom methods to be added to
// PacketCaptureNamespaceLister.
type PacketCaptureNamespaceListerExpansion interface{}

// ProfileListerExpansion allows custom methods to be added to
// ProfileLister.
type ProfileListerExpansion interface{}

// ProfileNamespaceListerExpansion allows custom methods to be added to
// ProfileNamespaceLister.
type ProfileNamespaceListerExpansion interface{}

// SecurityGroupListerExpansion allows custom methods to be added to
// SecurityGroupLister.
type SecurityGroupListerExpansion interface{}

// SecurityGroupNamespaceListerExpansion allows custom methods to be added to
// SecurityGroupNamespaceLister.
type SecurityGroupNamespaceListerExpansion interface{}

// SecurityRuleListerExpansion allows custom methods to be added to
// SecurityRuleLister.
type SecurityRuleListerExpansion interface{}

// SecurityRuleNamespaceListerExpansion allows custom methods to be added to
// SecurityRuleNamespaceLister.
type SecurityRuleNamespaceListerExpansion interface{}

// WatcherListerExpansion allows custom methods to be added to
// WatcherLister.
type WatcherListerExpansion interface{}

// WatcherNamespaceListerExpansion allows custom methods to be added to
// WatcherNamespaceLister.
type WatcherNamespaceListerExpansion interface{}

// WatcherFlowLogListerExpansion allows custom methods to be added to
// WatcherFlowLogLister.
type WatcherFlowLogListerExpansion interface{}

// WatcherFlowLogNamespaceListerExpansion allows custom methods to be added to
// WatcherFlowLogNamespaceLister.
type WatcherFlowLogNamespaceListerExpansion interface{}
