/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/apimanagement/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProductPolicies implements ProductPolicyInterface
type FakeProductPolicies struct {
	Fake *FakeApimanagementV1alpha1
	ns   string
}

var productpoliciesResource = schema.GroupVersionResource{Group: "apimanagement.azurerm.kubeform.com", Version: "v1alpha1", Resource: "productpolicies"}

var productpoliciesKind = schema.GroupVersionKind{Group: "apimanagement.azurerm.kubeform.com", Version: "v1alpha1", Kind: "ProductPolicy"}

// Get takes name of the productPolicy, and returns the corresponding productPolicy object, and an error if there is any.
func (c *FakeProductPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProductPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(productpoliciesResource, c.ns, name), &v1alpha1.ProductPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProductPolicy), err
}

// List takes label and field selectors, and returns the list of ProductPolicies that match those selectors.
func (c *FakeProductPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProductPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(productpoliciesResource, productpoliciesKind, c.ns, opts), &v1alpha1.ProductPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProductPolicyList{ListMeta: obj.(*v1alpha1.ProductPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProductPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested productPolicies.
func (c *FakeProductPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(productpoliciesResource, c.ns, opts))

}

// Create takes the representation of a productPolicy and creates it.  Returns the server's representation of the productPolicy, and an error, if there is any.
func (c *FakeProductPolicies) Create(ctx context.Context, productPolicy *v1alpha1.ProductPolicy, opts v1.CreateOptions) (result *v1alpha1.ProductPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(productpoliciesResource, c.ns, productPolicy), &v1alpha1.ProductPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProductPolicy), err
}

// Update takes the representation of a productPolicy and updates it. Returns the server's representation of the productPolicy, and an error, if there is any.
func (c *FakeProductPolicies) Update(ctx context.Context, productPolicy *v1alpha1.ProductPolicy, opts v1.UpdateOptions) (result *v1alpha1.ProductPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(productpoliciesResource, c.ns, productPolicy), &v1alpha1.ProductPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProductPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProductPolicies) UpdateStatus(ctx context.Context, productPolicy *v1alpha1.ProductPolicy, opts v1.UpdateOptions) (*v1alpha1.ProductPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(productpoliciesResource, "status", c.ns, productPolicy), &v1alpha1.ProductPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProductPolicy), err
}

// Delete takes name of the productPolicy and deletes it. Returns an error if one occurs.
func (c *FakeProductPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(productpoliciesResource, c.ns, name), &v1alpha1.ProductPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProductPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(productpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProductPolicyList{})
	return err
}

// Patch applies the patch and returns the patched productPolicy.
func (c *FakeProductPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProductPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(productpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ProductPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProductPolicy), err
}
