/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/apimanagement/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeApiOperations implements ApiOperationInterface
type FakeApiOperations struct {
	Fake *FakeApimanagementV1alpha1
	ns   string
}

var apioperationsResource = schema.GroupVersionResource{Group: "apimanagement.azurerm.kubeform.com", Version: "v1alpha1", Resource: "apioperations"}

var apioperationsKind = schema.GroupVersionKind{Group: "apimanagement.azurerm.kubeform.com", Version: "v1alpha1", Kind: "ApiOperation"}

// Get takes name of the apiOperation, and returns the corresponding apiOperation object, and an error if there is any.
func (c *FakeApiOperations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ApiOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apioperationsResource, c.ns, name), &v1alpha1.ApiOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApiOperation), err
}

// List takes label and field selectors, and returns the list of ApiOperations that match those selectors.
func (c *FakeApiOperations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ApiOperationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apioperationsResource, apioperationsKind, c.ns, opts), &v1alpha1.ApiOperationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ApiOperationList{ListMeta: obj.(*v1alpha1.ApiOperationList).ListMeta}
	for _, item := range obj.(*v1alpha1.ApiOperationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested apiOperations.
func (c *FakeApiOperations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apioperationsResource, c.ns, opts))

}

// Create takes the representation of a apiOperation and creates it.  Returns the server's representation of the apiOperation, and an error, if there is any.
func (c *FakeApiOperations) Create(ctx context.Context, apiOperation *v1alpha1.ApiOperation, opts v1.CreateOptions) (result *v1alpha1.ApiOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apioperationsResource, c.ns, apiOperation), &v1alpha1.ApiOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApiOperation), err
}

// Update takes the representation of a apiOperation and updates it. Returns the server's representation of the apiOperation, and an error, if there is any.
func (c *FakeApiOperations) Update(ctx context.Context, apiOperation *v1alpha1.ApiOperation, opts v1.UpdateOptions) (result *v1alpha1.ApiOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apioperationsResource, c.ns, apiOperation), &v1alpha1.ApiOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApiOperation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeApiOperations) UpdateStatus(ctx context.Context, apiOperation *v1alpha1.ApiOperation, opts v1.UpdateOptions) (*v1alpha1.ApiOperation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(apioperationsResource, "status", c.ns, apiOperation), &v1alpha1.ApiOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApiOperation), err
}

// Delete takes name of the apiOperation and deletes it. Returns an error if one occurs.
func (c *FakeApiOperations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(apioperationsResource, c.ns, name), &v1alpha1.ApiOperation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeApiOperations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apioperationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ApiOperationList{})
	return err
}

// Patch applies the patch and returns the patched apiOperation.
func (c *FakeApiOperations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ApiOperation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apioperationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ApiOperation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ApiOperation), err
}
