/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/bot/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChannelWebChats implements ChannelWebChatInterface
type FakeChannelWebChats struct {
	Fake *FakeBotV1alpha1
	ns   string
}

var channelwebchatsResource = schema.GroupVersionResource{Group: "bot.azurerm.kubeform.com", Version: "v1alpha1", Resource: "channelwebchats"}

var channelwebchatsKind = schema.GroupVersionKind{Group: "bot.azurerm.kubeform.com", Version: "v1alpha1", Kind: "ChannelWebChat"}

// Get takes name of the channelWebChat, and returns the corresponding channelWebChat object, and an error if there is any.
func (c *FakeChannelWebChats) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ChannelWebChat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(channelwebchatsResource, c.ns, name), &v1alpha1.ChannelWebChat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelWebChat), err
}

// List takes label and field selectors, and returns the list of ChannelWebChats that match those selectors.
func (c *FakeChannelWebChats) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ChannelWebChatList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(channelwebchatsResource, channelwebchatsKind, c.ns, opts), &v1alpha1.ChannelWebChatList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ChannelWebChatList{ListMeta: obj.(*v1alpha1.ChannelWebChatList).ListMeta}
	for _, item := range obj.(*v1alpha1.ChannelWebChatList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested channelWebChats.
func (c *FakeChannelWebChats) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(channelwebchatsResource, c.ns, opts))

}

// Create takes the representation of a channelWebChat and creates it.  Returns the server's representation of the channelWebChat, and an error, if there is any.
func (c *FakeChannelWebChats) Create(ctx context.Context, channelWebChat *v1alpha1.ChannelWebChat, opts v1.CreateOptions) (result *v1alpha1.ChannelWebChat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(channelwebchatsResource, c.ns, channelWebChat), &v1alpha1.ChannelWebChat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelWebChat), err
}

// Update takes the representation of a channelWebChat and updates it. Returns the server's representation of the channelWebChat, and an error, if there is any.
func (c *FakeChannelWebChats) Update(ctx context.Context, channelWebChat *v1alpha1.ChannelWebChat, opts v1.UpdateOptions) (result *v1alpha1.ChannelWebChat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(channelwebchatsResource, c.ns, channelWebChat), &v1alpha1.ChannelWebChat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelWebChat), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeChannelWebChats) UpdateStatus(ctx context.Context, channelWebChat *v1alpha1.ChannelWebChat, opts v1.UpdateOptions) (*v1alpha1.ChannelWebChat, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(channelwebchatsResource, "status", c.ns, channelWebChat), &v1alpha1.ChannelWebChat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelWebChat), err
}

// Delete takes name of the channelWebChat and deletes it. Returns an error if one occurs.
func (c *FakeChannelWebChats) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(channelwebchatsResource, c.ns, name), &v1alpha1.ChannelWebChat{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChannelWebChats) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(channelwebchatsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ChannelWebChatList{})
	return err
}

// Patch applies the patch and returns the patched channelWebChat.
func (c *FakeChannelWebChats) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ChannelWebChat, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(channelwebchatsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ChannelWebChat{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelWebChat), err
}
