/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/virtual/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHubRouteTableRoutes implements HubRouteTableRouteInterface
type FakeHubRouteTableRoutes struct {
	Fake *FakeVirtualV1alpha1
	ns   string
}

var hubroutetableroutesResource = schema.GroupVersionResource{Group: "virtual.azurerm.kubeform.com", Version: "v1alpha1", Resource: "hubroutetableroutes"}

var hubroutetableroutesKind = schema.GroupVersionKind{Group: "virtual.azurerm.kubeform.com", Version: "v1alpha1", Kind: "HubRouteTableRoute"}

// Get takes name of the hubRouteTableRoute, and returns the corresponding hubRouteTableRoute object, and an error if there is any.
func (c *FakeHubRouteTableRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HubRouteTableRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hubroutetableroutesResource, c.ns, name), &v1alpha1.HubRouteTableRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HubRouteTableRoute), err
}

// List takes label and field selectors, and returns the list of HubRouteTableRoutes that match those selectors.
func (c *FakeHubRouteTableRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HubRouteTableRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hubroutetableroutesResource, hubroutetableroutesKind, c.ns, opts), &v1alpha1.HubRouteTableRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HubRouteTableRouteList{ListMeta: obj.(*v1alpha1.HubRouteTableRouteList).ListMeta}
	for _, item := range obj.(*v1alpha1.HubRouteTableRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hubRouteTableRoutes.
func (c *FakeHubRouteTableRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hubroutetableroutesResource, c.ns, opts))

}

// Create takes the representation of a hubRouteTableRoute and creates it.  Returns the server's representation of the hubRouteTableRoute, and an error, if there is any.
func (c *FakeHubRouteTableRoutes) Create(ctx context.Context, hubRouteTableRoute *v1alpha1.HubRouteTableRoute, opts v1.CreateOptions) (result *v1alpha1.HubRouteTableRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hubroutetableroutesResource, c.ns, hubRouteTableRoute), &v1alpha1.HubRouteTableRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HubRouteTableRoute), err
}

// Update takes the representation of a hubRouteTableRoute and updates it. Returns the server's representation of the hubRouteTableRoute, and an error, if there is any.
func (c *FakeHubRouteTableRoutes) Update(ctx context.Context, hubRouteTableRoute *v1alpha1.HubRouteTableRoute, opts v1.UpdateOptions) (result *v1alpha1.HubRouteTableRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hubroutetableroutesResource, c.ns, hubRouteTableRoute), &v1alpha1.HubRouteTableRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HubRouteTableRoute), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHubRouteTableRoutes) UpdateStatus(ctx context.Context, hubRouteTableRoute *v1alpha1.HubRouteTableRoute, opts v1.UpdateOptions) (*v1alpha1.HubRouteTableRoute, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hubroutetableroutesResource, "status", c.ns, hubRouteTableRoute), &v1alpha1.HubRouteTableRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HubRouteTableRoute), err
}

// Delete takes name of the hubRouteTableRoute and deletes it. Returns an error if one occurs.
func (c *FakeHubRouteTableRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hubroutetableroutesResource, c.ns, name), &v1alpha1.HubRouteTableRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHubRouteTableRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hubroutetableroutesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HubRouteTableRouteList{})
	return err
}

// Patch applies the patch and returns the patched hubRouteTableRoute.
func (c *FakeHubRouteTableRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HubRouteTableRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hubroutetableroutesResource, c.ns, name, pt, data, subresources...), &v1alpha1.HubRouteTableRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HubRouteTableRoute), err
}
