/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "kubeform.dev/provider-azurerm-api/client/clientset/versioned"
	advancedv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/advanced/v1alpha1"
	fakeadvancedv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/advanced/v1alpha1/fake"
	analysisv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/analysis/v1alpha1"
	fakeanalysisv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/analysis/v1alpha1/fake"
	apimanagementv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/apimanagement/v1alpha1"
	fakeapimanagementv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/apimanagement/v1alpha1/fake"
	appv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/app/v1alpha1"
	fakeappv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/app/v1alpha1/fake"
	applicationv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/application/v1alpha1"
	fakeapplicationv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/application/v1alpha1/fake"
	attestationv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/attestation/v1alpha1"
	fakeattestationv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/attestation/v1alpha1/fake"
	automationv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/automation/v1alpha1"
	fakeautomationv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/automation/v1alpha1/fake"
	availabilityv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/availability/v1alpha1"
	fakeavailabilityv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/availability/v1alpha1/fake"
	backupv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/backup/v1alpha1"
	fakebackupv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/backup/v1alpha1/fake"
	bastionv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/bastion/v1alpha1"
	fakebastionv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/bastion/v1alpha1/fake"
	batchv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/batch/v1alpha1"
	fakebatchv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/batch/v1alpha1/fake"
	blueprintv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/blueprint/v1alpha1"
	fakeblueprintv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/blueprint/v1alpha1/fake"
	botv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/bot/v1alpha1"
	fakebotv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/bot/v1alpha1/fake"
	cdnv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/cdn/v1alpha1"
	fakecdnv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/cdn/v1alpha1/fake"
	cognitivev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/cognitive/v1alpha1"
	fakecognitivev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/cognitive/v1alpha1/fake"
	communicationv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/communication/v1alpha1"
	fakecommunicationv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/communication/v1alpha1/fake"
	consumptionv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/consumption/v1alpha1"
	fakeconsumptionv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/consumption/v1alpha1/fake"
	containerv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/container/v1alpha1"
	fakecontainerv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/container/v1alpha1/fake"
	cosmosdbv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/cosmosdb/v1alpha1"
	fakecosmosdbv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/cosmosdb/v1alpha1/fake"
	costv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/cost/v1alpha1"
	fakecostv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/cost/v1alpha1/fake"
	customv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/custom/v1alpha1"
	fakecustomv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/custom/v1alpha1/fake"
	dashboardv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/dashboard/v1alpha1"
	fakedashboardv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/dashboard/v1alpha1/fake"
	datav1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/data/v1alpha1"
	fakedatav1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/data/v1alpha1/fake"
	databasev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/database/v1alpha1"
	fakedatabasev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/database/v1alpha1/fake"
	databoxv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/databox/v1alpha1"
	fakedataboxv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/databox/v1alpha1/fake"
	databricksv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/databricks/v1alpha1"
	fakedatabricksv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/databricks/v1alpha1/fake"
	dedicatedhardwarev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/dedicatedhardware/v1alpha1"
	fakededicatedhardwarev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/dedicatedhardware/v1alpha1/fake"
	dedicatedhostv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/dedicatedhost/v1alpha1"
	fakededicatedhostv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/dedicatedhost/v1alpha1/fake"
	devspacev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/devspace/v1alpha1"
	fakedevspacev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/devspace/v1alpha1/fake"
	devtestv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/devtest/v1alpha1"
	fakedevtestv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/devtest/v1alpha1/fake"
	digitalv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/digital/v1alpha1"
	fakedigitalv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/digital/v1alpha1/fake"
	diskv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/disk/v1alpha1"
	fakediskv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/disk/v1alpha1/fake"
	dnsv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/dns/v1alpha1"
	fakednsv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/dns/v1alpha1/fake"
	eventgridv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/eventgrid/v1alpha1"
	fakeeventgridv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/eventgrid/v1alpha1/fake"
	eventhubv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/eventhub/v1alpha1"
	fakeeventhubv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/eventhub/v1alpha1/fake"
	expressroutev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/expressroute/v1alpha1"
	fakeexpressroutev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/expressroute/v1alpha1/fake"
	firewallv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/firewall/v1alpha1"
	fakefirewallv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/firewall/v1alpha1/fake"
	frontdoorv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/frontdoor/v1alpha1"
	fakefrontdoorv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/frontdoor/v1alpha1/fake"
	functionv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/function/v1alpha1"
	fakefunctionv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/function/v1alpha1/fake"
	hdinsightv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/hdinsight/v1alpha1"
	fakehdinsightv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/hdinsight/v1alpha1/fake"
	healthbotv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/healthbot/v1alpha1"
	fakehealthbotv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/healthbot/v1alpha1/fake"
	healthcarev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/healthcare/v1alpha1"
	fakehealthcarev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/healthcare/v1alpha1/fake"
	hpcv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/hpc/v1alpha1"
	fakehpcv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/hpc/v1alpha1/fake"
	imagev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/image/v1alpha1"
	fakeimagev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/image/v1alpha1/fake"
	integrationv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/integration/v1alpha1"
	fakeintegrationv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/integration/v1alpha1/fake"
	iotcentralv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/iotcentral/v1alpha1"
	fakeiotcentralv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/iotcentral/v1alpha1/fake"
	iothubv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/iothub/v1alpha1"
	fakeiothubv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/iothub/v1alpha1/fake"
	iotsecurityv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/iotsecurity/v1alpha1"
	fakeiotsecurityv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/iotsecurity/v1alpha1/fake"
	iottimev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/iottime/v1alpha1"
	fakeiottimev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/iottime/v1alpha1/fake"
	ipv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/ip/v1alpha1"
	fakeipv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/ip/v1alpha1/fake"
	keyvaultv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/keyvault/v1alpha1"
	fakekeyvaultv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/keyvault/v1alpha1/fake"
	kubernetesclusterv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/kubernetescluster/v1alpha1"
	fakekubernetesclusterv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/kubernetescluster/v1alpha1/fake"
	kustov1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/kusto/v1alpha1"
	fakekustov1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/kusto/v1alpha1/fake"
	lbv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/lb/v1alpha1"
	fakelbv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/lb/v1alpha1/fake"
	lighthousev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/lighthouse/v1alpha1"
	fakelighthousev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/lighthouse/v1alpha1/fake"
	linuxv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/linux/v1alpha1"
	fakelinuxv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/linux/v1alpha1/fake"
	localv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/local/v1alpha1"
	fakelocalv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/local/v1alpha1/fake"
	loganalyticsv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/loganalytics/v1alpha1"
	fakeloganalyticsv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/loganalytics/v1alpha1/fake"
	logicappv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/logicapp/v1alpha1"
	fakelogicappv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/logicapp/v1alpha1/fake"
	machinev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/machine/v1alpha1"
	fakemachinev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/machine/v1alpha1/fake"
	maintenancev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/maintenance/v1alpha1"
	fakemaintenancev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/maintenance/v1alpha1/fake"
	managedv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/managed/v1alpha1"
	fakemanagedv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/managed/v1alpha1/fake"
	managementv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/management/v1alpha1"
	fakemanagementv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/management/v1alpha1/fake"
	mapsv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/maps/v1alpha1"
	fakemapsv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/maps/v1alpha1/fake"
	mariadbv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/mariadb/v1alpha1"
	fakemariadbv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/mariadb/v1alpha1/fake"
	marketplacev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/marketplace/v1alpha1"
	fakemarketplacev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/marketplace/v1alpha1/fake"
	mediav1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/media/v1alpha1"
	fakemediav1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/media/v1alpha1/fake"
	monitorv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/monitor/v1alpha1"
	fakemonitorv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/monitor/v1alpha1/fake"
	mssqlv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/mssql/v1alpha1"
	fakemssqlv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/mssql/v1alpha1/fake"
	mysqlv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/mysql/v1alpha1"
	fakemysqlv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/mysql/v1alpha1/fake"
	natv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/nat/v1alpha1"
	fakenatv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/nat/v1alpha1/fake"
	netappv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/netapp/v1alpha1"
	fakenetappv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/netapp/v1alpha1/fake"
	networkv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/network/v1alpha1"
	fakenetworkv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/network/v1alpha1/fake"
	notificationhubv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/notificationhub/v1alpha1"
	fakenotificationhubv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/notificationhub/v1alpha1/fake"
	orchestratedv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/orchestrated/v1alpha1"
	fakeorchestratedv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/orchestrated/v1alpha1/fake"
	packetv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/packet/v1alpha1"
	fakepacketv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/packet/v1alpha1/fake"
	pointv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/point/v1alpha1"
	fakepointv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/point/v1alpha1/fake"
	policyv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/policy/v1alpha1"
	fakepolicyv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/policy/v1alpha1/fake"
	portalv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/portal/v1alpha1"
	fakeportalv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/portal/v1alpha1/fake"
	postgresqlv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/postgresql/v1alpha1"
	fakepostgresqlv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/postgresql/v1alpha1/fake"
	powerbiv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/powerbi/v1alpha1"
	fakepowerbiv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/powerbi/v1alpha1/fake"
	privatev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/private/v1alpha1"
	fakeprivatev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/private/v1alpha1/fake"
	proximityv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/proximity/v1alpha1"
	fakeproximityv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/proximity/v1alpha1/fake"
	publicipv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/publicip/v1alpha1"
	fakepublicipv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/publicip/v1alpha1/fake"
	purviewv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/purview/v1alpha1"
	fakepurviewv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/purview/v1alpha1/fake"
	recoveryv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/recovery/v1alpha1"
	fakerecoveryv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/recovery/v1alpha1/fake"
	redisv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/redis/v1alpha1"
	fakeredisv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/redis/v1alpha1/fake"
	relayv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/relay/v1alpha1"
	fakerelayv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/relay/v1alpha1/fake"
	resourcev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/resource/v1alpha1"
	fakeresourcev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/resource/v1alpha1/fake"
	rolev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/role/v1alpha1"
	fakerolev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/role/v1alpha1/fake"
	routev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/route/v1alpha1"
	fakeroutev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/route/v1alpha1/fake"
	searchv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/search/v1alpha1"
	fakesearchv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/search/v1alpha1/fake"
	securityv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/security/v1alpha1"
	fakesecurityv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/security/v1alpha1/fake"
	sentinelv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/sentinel/v1alpha1"
	fakesentinelv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/sentinel/v1alpha1/fake"
	servicev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/service/v1alpha1"
	fakeservicev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/service/v1alpha1/fake"
	servicebusv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/servicebus/v1alpha1"
	fakeservicebusv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/servicebus/v1alpha1/fake"
	sharedimagev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/sharedimage/v1alpha1"
	fakesharedimagev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/sharedimage/v1alpha1/fake"
	signalrv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/signalr/v1alpha1"
	fakesignalrv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/signalr/v1alpha1/fake"
	siterecoveryv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/siterecovery/v1alpha1"
	fakesiterecoveryv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/siterecovery/v1alpha1/fake"
	snapshotv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/snapshot/v1alpha1"
	fakesnapshotv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/snapshot/v1alpha1/fake"
	spatialv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/spatial/v1alpha1"
	fakespatialv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/spatial/v1alpha1/fake"
	springv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/spring/v1alpha1"
	fakespringv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/spring/v1alpha1/fake"
	sqlv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/sql/v1alpha1"
	fakesqlv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/sql/v1alpha1/fake"
	sshv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/ssh/v1alpha1"
	fakesshv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/ssh/v1alpha1/fake"
	stackv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/stack/v1alpha1"
	fakestackv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/stack/v1alpha1/fake"
	staticv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/static/v1alpha1"
	fakestaticv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/static/v1alpha1/fake"
	storagev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/storage/v1alpha1"
	fakestoragev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/storage/v1alpha1/fake"
	streamv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/stream/v1alpha1"
	fakestreamv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/stream/v1alpha1/fake"
	subnetv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/subnet/v1alpha1"
	fakesubnetv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/subnet/v1alpha1/fake"
	subscriptionv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/subscription/v1alpha1"
	fakesubscriptionv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/subscription/v1alpha1/fake"
	synapsev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/synapse/v1alpha1"
	fakesynapsev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/synapse/v1alpha1/fake"
	templatev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/template/v1alpha1"
	faketemplatev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/template/v1alpha1/fake"
	tenantv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/tenant/v1alpha1"
	faketenantv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/tenant/v1alpha1/fake"
	trafficmanagerv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/trafficmanager/v1alpha1"
	faketrafficmanagerv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/trafficmanager/v1alpha1/fake"
	userv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/user/v1alpha1"
	fakeuserv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/user/v1alpha1/fake"
	virtualv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/virtual/v1alpha1"
	fakevirtualv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/virtual/v1alpha1/fake"
	vmwarev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/vmware/v1alpha1"
	fakevmwarev1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/vmware/v1alpha1/fake"
	vpnv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/vpn/v1alpha1"
	fakevpnv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/vpn/v1alpha1/fake"
	webv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/web/v1alpha1"
	fakewebv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/web/v1alpha1/fake"
	windowsv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/windows/v1alpha1"
	fakewindowsv1alpha1 "kubeform.dev/provider-azurerm-api/client/clientset/versioned/typed/windows/v1alpha1/fake"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var _ clientset.Interface = &Clientset{}

// AdvancedV1alpha1 retrieves the AdvancedV1alpha1Client
func (c *Clientset) AdvancedV1alpha1() advancedv1alpha1.AdvancedV1alpha1Interface {
	return &fakeadvancedv1alpha1.FakeAdvancedV1alpha1{Fake: &c.Fake}
}

// AnalysisV1alpha1 retrieves the AnalysisV1alpha1Client
func (c *Clientset) AnalysisV1alpha1() analysisv1alpha1.AnalysisV1alpha1Interface {
	return &fakeanalysisv1alpha1.FakeAnalysisV1alpha1{Fake: &c.Fake}
}

// ApimanagementV1alpha1 retrieves the ApimanagementV1alpha1Client
func (c *Clientset) ApimanagementV1alpha1() apimanagementv1alpha1.ApimanagementV1alpha1Interface {
	return &fakeapimanagementv1alpha1.FakeApimanagementV1alpha1{Fake: &c.Fake}
}

// AppV1alpha1 retrieves the AppV1alpha1Client
func (c *Clientset) AppV1alpha1() appv1alpha1.AppV1alpha1Interface {
	return &fakeappv1alpha1.FakeAppV1alpha1{Fake: &c.Fake}
}

// ApplicationV1alpha1 retrieves the ApplicationV1alpha1Client
func (c *Clientset) ApplicationV1alpha1() applicationv1alpha1.ApplicationV1alpha1Interface {
	return &fakeapplicationv1alpha1.FakeApplicationV1alpha1{Fake: &c.Fake}
}

// AttestationV1alpha1 retrieves the AttestationV1alpha1Client
func (c *Clientset) AttestationV1alpha1() attestationv1alpha1.AttestationV1alpha1Interface {
	return &fakeattestationv1alpha1.FakeAttestationV1alpha1{Fake: &c.Fake}
}

// AutomationV1alpha1 retrieves the AutomationV1alpha1Client
func (c *Clientset) AutomationV1alpha1() automationv1alpha1.AutomationV1alpha1Interface {
	return &fakeautomationv1alpha1.FakeAutomationV1alpha1{Fake: &c.Fake}
}

// AvailabilityV1alpha1 retrieves the AvailabilityV1alpha1Client
func (c *Clientset) AvailabilityV1alpha1() availabilityv1alpha1.AvailabilityV1alpha1Interface {
	return &fakeavailabilityv1alpha1.FakeAvailabilityV1alpha1{Fake: &c.Fake}
}

// BackupV1alpha1 retrieves the BackupV1alpha1Client
func (c *Clientset) BackupV1alpha1() backupv1alpha1.BackupV1alpha1Interface {
	return &fakebackupv1alpha1.FakeBackupV1alpha1{Fake: &c.Fake}
}

// BastionV1alpha1 retrieves the BastionV1alpha1Client
func (c *Clientset) BastionV1alpha1() bastionv1alpha1.BastionV1alpha1Interface {
	return &fakebastionv1alpha1.FakeBastionV1alpha1{Fake: &c.Fake}
}

// BatchV1alpha1 retrieves the BatchV1alpha1Client
func (c *Clientset) BatchV1alpha1() batchv1alpha1.BatchV1alpha1Interface {
	return &fakebatchv1alpha1.FakeBatchV1alpha1{Fake: &c.Fake}
}

// BlueprintV1alpha1 retrieves the BlueprintV1alpha1Client
func (c *Clientset) BlueprintV1alpha1() blueprintv1alpha1.BlueprintV1alpha1Interface {
	return &fakeblueprintv1alpha1.FakeBlueprintV1alpha1{Fake: &c.Fake}
}

// BotV1alpha1 retrieves the BotV1alpha1Client
func (c *Clientset) BotV1alpha1() botv1alpha1.BotV1alpha1Interface {
	return &fakebotv1alpha1.FakeBotV1alpha1{Fake: &c.Fake}
}

// CdnV1alpha1 retrieves the CdnV1alpha1Client
func (c *Clientset) CdnV1alpha1() cdnv1alpha1.CdnV1alpha1Interface {
	return &fakecdnv1alpha1.FakeCdnV1alpha1{Fake: &c.Fake}
}

// CognitiveV1alpha1 retrieves the CognitiveV1alpha1Client
func (c *Clientset) CognitiveV1alpha1() cognitivev1alpha1.CognitiveV1alpha1Interface {
	return &fakecognitivev1alpha1.FakeCognitiveV1alpha1{Fake: &c.Fake}
}

// CommunicationV1alpha1 retrieves the CommunicationV1alpha1Client
func (c *Clientset) CommunicationV1alpha1() communicationv1alpha1.CommunicationV1alpha1Interface {
	return &fakecommunicationv1alpha1.FakeCommunicationV1alpha1{Fake: &c.Fake}
}

// ConsumptionV1alpha1 retrieves the ConsumptionV1alpha1Client
func (c *Clientset) ConsumptionV1alpha1() consumptionv1alpha1.ConsumptionV1alpha1Interface {
	return &fakeconsumptionv1alpha1.FakeConsumptionV1alpha1{Fake: &c.Fake}
}

// ContainerV1alpha1 retrieves the ContainerV1alpha1Client
func (c *Clientset) ContainerV1alpha1() containerv1alpha1.ContainerV1alpha1Interface {
	return &fakecontainerv1alpha1.FakeContainerV1alpha1{Fake: &c.Fake}
}

// CosmosdbV1alpha1 retrieves the CosmosdbV1alpha1Client
func (c *Clientset) CosmosdbV1alpha1() cosmosdbv1alpha1.CosmosdbV1alpha1Interface {
	return &fakecosmosdbv1alpha1.FakeCosmosdbV1alpha1{Fake: &c.Fake}
}

// CostV1alpha1 retrieves the CostV1alpha1Client
func (c *Clientset) CostV1alpha1() costv1alpha1.CostV1alpha1Interface {
	return &fakecostv1alpha1.FakeCostV1alpha1{Fake: &c.Fake}
}

// CustomV1alpha1 retrieves the CustomV1alpha1Client
func (c *Clientset) CustomV1alpha1() customv1alpha1.CustomV1alpha1Interface {
	return &fakecustomv1alpha1.FakeCustomV1alpha1{Fake: &c.Fake}
}

// DashboardV1alpha1 retrieves the DashboardV1alpha1Client
func (c *Clientset) DashboardV1alpha1() dashboardv1alpha1.DashboardV1alpha1Interface {
	return &fakedashboardv1alpha1.FakeDashboardV1alpha1{Fake: &c.Fake}
}

// DataV1alpha1 retrieves the DataV1alpha1Client
func (c *Clientset) DataV1alpha1() datav1alpha1.DataV1alpha1Interface {
	return &fakedatav1alpha1.FakeDataV1alpha1{Fake: &c.Fake}
}

// DatabaseV1alpha1 retrieves the DatabaseV1alpha1Client
func (c *Clientset) DatabaseV1alpha1() databasev1alpha1.DatabaseV1alpha1Interface {
	return &fakedatabasev1alpha1.FakeDatabaseV1alpha1{Fake: &c.Fake}
}

// DataboxV1alpha1 retrieves the DataboxV1alpha1Client
func (c *Clientset) DataboxV1alpha1() databoxv1alpha1.DataboxV1alpha1Interface {
	return &fakedataboxv1alpha1.FakeDataboxV1alpha1{Fake: &c.Fake}
}

// DatabricksV1alpha1 retrieves the DatabricksV1alpha1Client
func (c *Clientset) DatabricksV1alpha1() databricksv1alpha1.DatabricksV1alpha1Interface {
	return &fakedatabricksv1alpha1.FakeDatabricksV1alpha1{Fake: &c.Fake}
}

// DedicatedhardwareV1alpha1 retrieves the DedicatedhardwareV1alpha1Client
func (c *Clientset) DedicatedhardwareV1alpha1() dedicatedhardwarev1alpha1.DedicatedhardwareV1alpha1Interface {
	return &fakededicatedhardwarev1alpha1.FakeDedicatedhardwareV1alpha1{Fake: &c.Fake}
}

// DedicatedhostV1alpha1 retrieves the DedicatedhostV1alpha1Client
func (c *Clientset) DedicatedhostV1alpha1() dedicatedhostv1alpha1.DedicatedhostV1alpha1Interface {
	return &fakededicatedhostv1alpha1.FakeDedicatedhostV1alpha1{Fake: &c.Fake}
}

// DevspaceV1alpha1 retrieves the DevspaceV1alpha1Client
func (c *Clientset) DevspaceV1alpha1() devspacev1alpha1.DevspaceV1alpha1Interface {
	return &fakedevspacev1alpha1.FakeDevspaceV1alpha1{Fake: &c.Fake}
}

// DevtestV1alpha1 retrieves the DevtestV1alpha1Client
func (c *Clientset) DevtestV1alpha1() devtestv1alpha1.DevtestV1alpha1Interface {
	return &fakedevtestv1alpha1.FakeDevtestV1alpha1{Fake: &c.Fake}
}

// DigitalV1alpha1 retrieves the DigitalV1alpha1Client
func (c *Clientset) DigitalV1alpha1() digitalv1alpha1.DigitalV1alpha1Interface {
	return &fakedigitalv1alpha1.FakeDigitalV1alpha1{Fake: &c.Fake}
}

// DiskV1alpha1 retrieves the DiskV1alpha1Client
func (c *Clientset) DiskV1alpha1() diskv1alpha1.DiskV1alpha1Interface {
	return &fakediskv1alpha1.FakeDiskV1alpha1{Fake: &c.Fake}
}

// DnsV1alpha1 retrieves the DnsV1alpha1Client
func (c *Clientset) DnsV1alpha1() dnsv1alpha1.DnsV1alpha1Interface {
	return &fakednsv1alpha1.FakeDnsV1alpha1{Fake: &c.Fake}
}

// EventgridV1alpha1 retrieves the EventgridV1alpha1Client
func (c *Clientset) EventgridV1alpha1() eventgridv1alpha1.EventgridV1alpha1Interface {
	return &fakeeventgridv1alpha1.FakeEventgridV1alpha1{Fake: &c.Fake}
}

// EventhubV1alpha1 retrieves the EventhubV1alpha1Client
func (c *Clientset) EventhubV1alpha1() eventhubv1alpha1.EventhubV1alpha1Interface {
	return &fakeeventhubv1alpha1.FakeEventhubV1alpha1{Fake: &c.Fake}
}

// ExpressrouteV1alpha1 retrieves the ExpressrouteV1alpha1Client
func (c *Clientset) ExpressrouteV1alpha1() expressroutev1alpha1.ExpressrouteV1alpha1Interface {
	return &fakeexpressroutev1alpha1.FakeExpressrouteV1alpha1{Fake: &c.Fake}
}

// FirewallV1alpha1 retrieves the FirewallV1alpha1Client
func (c *Clientset) FirewallV1alpha1() firewallv1alpha1.FirewallV1alpha1Interface {
	return &fakefirewallv1alpha1.FakeFirewallV1alpha1{Fake: &c.Fake}
}

// FrontdoorV1alpha1 retrieves the FrontdoorV1alpha1Client
func (c *Clientset) FrontdoorV1alpha1() frontdoorv1alpha1.FrontdoorV1alpha1Interface {
	return &fakefrontdoorv1alpha1.FakeFrontdoorV1alpha1{Fake: &c.Fake}
}

// FunctionV1alpha1 retrieves the FunctionV1alpha1Client
func (c *Clientset) FunctionV1alpha1() functionv1alpha1.FunctionV1alpha1Interface {
	return &fakefunctionv1alpha1.FakeFunctionV1alpha1{Fake: &c.Fake}
}

// HdinsightV1alpha1 retrieves the HdinsightV1alpha1Client
func (c *Clientset) HdinsightV1alpha1() hdinsightv1alpha1.HdinsightV1alpha1Interface {
	return &fakehdinsightv1alpha1.FakeHdinsightV1alpha1{Fake: &c.Fake}
}

// HealthbotV1alpha1 retrieves the HealthbotV1alpha1Client
func (c *Clientset) HealthbotV1alpha1() healthbotv1alpha1.HealthbotV1alpha1Interface {
	return &fakehealthbotv1alpha1.FakeHealthbotV1alpha1{Fake: &c.Fake}
}

// HealthcareV1alpha1 retrieves the HealthcareV1alpha1Client
func (c *Clientset) HealthcareV1alpha1() healthcarev1alpha1.HealthcareV1alpha1Interface {
	return &fakehealthcarev1alpha1.FakeHealthcareV1alpha1{Fake: &c.Fake}
}

// HpcV1alpha1 retrieves the HpcV1alpha1Client
func (c *Clientset) HpcV1alpha1() hpcv1alpha1.HpcV1alpha1Interface {
	return &fakehpcv1alpha1.FakeHpcV1alpha1{Fake: &c.Fake}
}

// ImageV1alpha1 retrieves the ImageV1alpha1Client
func (c *Clientset) ImageV1alpha1() imagev1alpha1.ImageV1alpha1Interface {
	return &fakeimagev1alpha1.FakeImageV1alpha1{Fake: &c.Fake}
}

// IntegrationV1alpha1 retrieves the IntegrationV1alpha1Client
func (c *Clientset) IntegrationV1alpha1() integrationv1alpha1.IntegrationV1alpha1Interface {
	return &fakeintegrationv1alpha1.FakeIntegrationV1alpha1{Fake: &c.Fake}
}

// IotcentralV1alpha1 retrieves the IotcentralV1alpha1Client
func (c *Clientset) IotcentralV1alpha1() iotcentralv1alpha1.IotcentralV1alpha1Interface {
	return &fakeiotcentralv1alpha1.FakeIotcentralV1alpha1{Fake: &c.Fake}
}

// IothubV1alpha1 retrieves the IothubV1alpha1Client
func (c *Clientset) IothubV1alpha1() iothubv1alpha1.IothubV1alpha1Interface {
	return &fakeiothubv1alpha1.FakeIothubV1alpha1{Fake: &c.Fake}
}

// IotsecurityV1alpha1 retrieves the IotsecurityV1alpha1Client
func (c *Clientset) IotsecurityV1alpha1() iotsecurityv1alpha1.IotsecurityV1alpha1Interface {
	return &fakeiotsecurityv1alpha1.FakeIotsecurityV1alpha1{Fake: &c.Fake}
}

// IottimeV1alpha1 retrieves the IottimeV1alpha1Client
func (c *Clientset) IottimeV1alpha1() iottimev1alpha1.IottimeV1alpha1Interface {
	return &fakeiottimev1alpha1.FakeIottimeV1alpha1{Fake: &c.Fake}
}

// IpV1alpha1 retrieves the IpV1alpha1Client
func (c *Clientset) IpV1alpha1() ipv1alpha1.IpV1alpha1Interface {
	return &fakeipv1alpha1.FakeIpV1alpha1{Fake: &c.Fake}
}

// KeyvaultV1alpha1 retrieves the KeyvaultV1alpha1Client
func (c *Clientset) KeyvaultV1alpha1() keyvaultv1alpha1.KeyvaultV1alpha1Interface {
	return &fakekeyvaultv1alpha1.FakeKeyvaultV1alpha1{Fake: &c.Fake}
}

// KubernetesclusterV1alpha1 retrieves the KubernetesclusterV1alpha1Client
func (c *Clientset) KubernetesclusterV1alpha1() kubernetesclusterv1alpha1.KubernetesclusterV1alpha1Interface {
	return &fakekubernetesclusterv1alpha1.FakeKubernetesclusterV1alpha1{Fake: &c.Fake}
}

// KustoV1alpha1 retrieves the KustoV1alpha1Client
func (c *Clientset) KustoV1alpha1() kustov1alpha1.KustoV1alpha1Interface {
	return &fakekustov1alpha1.FakeKustoV1alpha1{Fake: &c.Fake}
}

// LbV1alpha1 retrieves the LbV1alpha1Client
func (c *Clientset) LbV1alpha1() lbv1alpha1.LbV1alpha1Interface {
	return &fakelbv1alpha1.FakeLbV1alpha1{Fake: &c.Fake}
}

// LighthouseV1alpha1 retrieves the LighthouseV1alpha1Client
func (c *Clientset) LighthouseV1alpha1() lighthousev1alpha1.LighthouseV1alpha1Interface {
	return &fakelighthousev1alpha1.FakeLighthouseV1alpha1{Fake: &c.Fake}
}

// LinuxV1alpha1 retrieves the LinuxV1alpha1Client
func (c *Clientset) LinuxV1alpha1() linuxv1alpha1.LinuxV1alpha1Interface {
	return &fakelinuxv1alpha1.FakeLinuxV1alpha1{Fake: &c.Fake}
}

// LocalV1alpha1 retrieves the LocalV1alpha1Client
func (c *Clientset) LocalV1alpha1() localv1alpha1.LocalV1alpha1Interface {
	return &fakelocalv1alpha1.FakeLocalV1alpha1{Fake: &c.Fake}
}

// LoganalyticsV1alpha1 retrieves the LoganalyticsV1alpha1Client
func (c *Clientset) LoganalyticsV1alpha1() loganalyticsv1alpha1.LoganalyticsV1alpha1Interface {
	return &fakeloganalyticsv1alpha1.FakeLoganalyticsV1alpha1{Fake: &c.Fake}
}

// LogicappV1alpha1 retrieves the LogicappV1alpha1Client
func (c *Clientset) LogicappV1alpha1() logicappv1alpha1.LogicappV1alpha1Interface {
	return &fakelogicappv1alpha1.FakeLogicappV1alpha1{Fake: &c.Fake}
}

// MachineV1alpha1 retrieves the MachineV1alpha1Client
func (c *Clientset) MachineV1alpha1() machinev1alpha1.MachineV1alpha1Interface {
	return &fakemachinev1alpha1.FakeMachineV1alpha1{Fake: &c.Fake}
}

// MaintenanceV1alpha1 retrieves the MaintenanceV1alpha1Client
func (c *Clientset) MaintenanceV1alpha1() maintenancev1alpha1.MaintenanceV1alpha1Interface {
	return &fakemaintenancev1alpha1.FakeMaintenanceV1alpha1{Fake: &c.Fake}
}

// ManagedV1alpha1 retrieves the ManagedV1alpha1Client
func (c *Clientset) ManagedV1alpha1() managedv1alpha1.ManagedV1alpha1Interface {
	return &fakemanagedv1alpha1.FakeManagedV1alpha1{Fake: &c.Fake}
}

// ManagementV1alpha1 retrieves the ManagementV1alpha1Client
func (c *Clientset) ManagementV1alpha1() managementv1alpha1.ManagementV1alpha1Interface {
	return &fakemanagementv1alpha1.FakeManagementV1alpha1{Fake: &c.Fake}
}

// MapsV1alpha1 retrieves the MapsV1alpha1Client
func (c *Clientset) MapsV1alpha1() mapsv1alpha1.MapsV1alpha1Interface {
	return &fakemapsv1alpha1.FakeMapsV1alpha1{Fake: &c.Fake}
}

// MariadbV1alpha1 retrieves the MariadbV1alpha1Client
func (c *Clientset) MariadbV1alpha1() mariadbv1alpha1.MariadbV1alpha1Interface {
	return &fakemariadbv1alpha1.FakeMariadbV1alpha1{Fake: &c.Fake}
}

// MarketplaceV1alpha1 retrieves the MarketplaceV1alpha1Client
func (c *Clientset) MarketplaceV1alpha1() marketplacev1alpha1.MarketplaceV1alpha1Interface {
	return &fakemarketplacev1alpha1.FakeMarketplaceV1alpha1{Fake: &c.Fake}
}

// MediaV1alpha1 retrieves the MediaV1alpha1Client
func (c *Clientset) MediaV1alpha1() mediav1alpha1.MediaV1alpha1Interface {
	return &fakemediav1alpha1.FakeMediaV1alpha1{Fake: &c.Fake}
}

// MonitorV1alpha1 retrieves the MonitorV1alpha1Client
func (c *Clientset) MonitorV1alpha1() monitorv1alpha1.MonitorV1alpha1Interface {
	return &fakemonitorv1alpha1.FakeMonitorV1alpha1{Fake: &c.Fake}
}

// MssqlV1alpha1 retrieves the MssqlV1alpha1Client
func (c *Clientset) MssqlV1alpha1() mssqlv1alpha1.MssqlV1alpha1Interface {
	return &fakemssqlv1alpha1.FakeMssqlV1alpha1{Fake: &c.Fake}
}

// MysqlV1alpha1 retrieves the MysqlV1alpha1Client
func (c *Clientset) MysqlV1alpha1() mysqlv1alpha1.MysqlV1alpha1Interface {
	return &fakemysqlv1alpha1.FakeMysqlV1alpha1{Fake: &c.Fake}
}

// NatV1alpha1 retrieves the NatV1alpha1Client
func (c *Clientset) NatV1alpha1() natv1alpha1.NatV1alpha1Interface {
	return &fakenatv1alpha1.FakeNatV1alpha1{Fake: &c.Fake}
}

// NetappV1alpha1 retrieves the NetappV1alpha1Client
func (c *Clientset) NetappV1alpha1() netappv1alpha1.NetappV1alpha1Interface {
	return &fakenetappv1alpha1.FakeNetappV1alpha1{Fake: &c.Fake}
}

// NetworkV1alpha1 retrieves the NetworkV1alpha1Client
func (c *Clientset) NetworkV1alpha1() networkv1alpha1.NetworkV1alpha1Interface {
	return &fakenetworkv1alpha1.FakeNetworkV1alpha1{Fake: &c.Fake}
}

// NotificationhubV1alpha1 retrieves the NotificationhubV1alpha1Client
func (c *Clientset) NotificationhubV1alpha1() notificationhubv1alpha1.NotificationhubV1alpha1Interface {
	return &fakenotificationhubv1alpha1.FakeNotificationhubV1alpha1{Fake: &c.Fake}
}

// OrchestratedV1alpha1 retrieves the OrchestratedV1alpha1Client
func (c *Clientset) OrchestratedV1alpha1() orchestratedv1alpha1.OrchestratedV1alpha1Interface {
	return &fakeorchestratedv1alpha1.FakeOrchestratedV1alpha1{Fake: &c.Fake}
}

// PacketV1alpha1 retrieves the PacketV1alpha1Client
func (c *Clientset) PacketV1alpha1() packetv1alpha1.PacketV1alpha1Interface {
	return &fakepacketv1alpha1.FakePacketV1alpha1{Fake: &c.Fake}
}

// PointV1alpha1 retrieves the PointV1alpha1Client
func (c *Clientset) PointV1alpha1() pointv1alpha1.PointV1alpha1Interface {
	return &fakepointv1alpha1.FakePointV1alpha1{Fake: &c.Fake}
}

// PolicyV1alpha1 retrieves the PolicyV1alpha1Client
func (c *Clientset) PolicyV1alpha1() policyv1alpha1.PolicyV1alpha1Interface {
	return &fakepolicyv1alpha1.FakePolicyV1alpha1{Fake: &c.Fake}
}

// PortalV1alpha1 retrieves the PortalV1alpha1Client
func (c *Clientset) PortalV1alpha1() portalv1alpha1.PortalV1alpha1Interface {
	return &fakeportalv1alpha1.FakePortalV1alpha1{Fake: &c.Fake}
}

// PostgresqlV1alpha1 retrieves the PostgresqlV1alpha1Client
func (c *Clientset) PostgresqlV1alpha1() postgresqlv1alpha1.PostgresqlV1alpha1Interface {
	return &fakepostgresqlv1alpha1.FakePostgresqlV1alpha1{Fake: &c.Fake}
}

// PowerbiV1alpha1 retrieves the PowerbiV1alpha1Client
func (c *Clientset) PowerbiV1alpha1() powerbiv1alpha1.PowerbiV1alpha1Interface {
	return &fakepowerbiv1alpha1.FakePowerbiV1alpha1{Fake: &c.Fake}
}

// PrivateV1alpha1 retrieves the PrivateV1alpha1Client
func (c *Clientset) PrivateV1alpha1() privatev1alpha1.PrivateV1alpha1Interface {
	return &fakeprivatev1alpha1.FakePrivateV1alpha1{Fake: &c.Fake}
}

// ProximityV1alpha1 retrieves the ProximityV1alpha1Client
func (c *Clientset) ProximityV1alpha1() proximityv1alpha1.ProximityV1alpha1Interface {
	return &fakeproximityv1alpha1.FakeProximityV1alpha1{Fake: &c.Fake}
}

// PublicipV1alpha1 retrieves the PublicipV1alpha1Client
func (c *Clientset) PublicipV1alpha1() publicipv1alpha1.PublicipV1alpha1Interface {
	return &fakepublicipv1alpha1.FakePublicipV1alpha1{Fake: &c.Fake}
}

// PurviewV1alpha1 retrieves the PurviewV1alpha1Client
func (c *Clientset) PurviewV1alpha1() purviewv1alpha1.PurviewV1alpha1Interface {
	return &fakepurviewv1alpha1.FakePurviewV1alpha1{Fake: &c.Fake}
}

// RecoveryV1alpha1 retrieves the RecoveryV1alpha1Client
func (c *Clientset) RecoveryV1alpha1() recoveryv1alpha1.RecoveryV1alpha1Interface {
	return &fakerecoveryv1alpha1.FakeRecoveryV1alpha1{Fake: &c.Fake}
}

// RedisV1alpha1 retrieves the RedisV1alpha1Client
func (c *Clientset) RedisV1alpha1() redisv1alpha1.RedisV1alpha1Interface {
	return &fakeredisv1alpha1.FakeRedisV1alpha1{Fake: &c.Fake}
}

// RelayV1alpha1 retrieves the RelayV1alpha1Client
func (c *Clientset) RelayV1alpha1() relayv1alpha1.RelayV1alpha1Interface {
	return &fakerelayv1alpha1.FakeRelayV1alpha1{Fake: &c.Fake}
}

// ResourceV1alpha1 retrieves the ResourceV1alpha1Client
func (c *Clientset) ResourceV1alpha1() resourcev1alpha1.ResourceV1alpha1Interface {
	return &fakeresourcev1alpha1.FakeResourceV1alpha1{Fake: &c.Fake}
}

// RoleV1alpha1 retrieves the RoleV1alpha1Client
func (c *Clientset) RoleV1alpha1() rolev1alpha1.RoleV1alpha1Interface {
	return &fakerolev1alpha1.FakeRoleV1alpha1{Fake: &c.Fake}
}

// RouteV1alpha1 retrieves the RouteV1alpha1Client
func (c *Clientset) RouteV1alpha1() routev1alpha1.RouteV1alpha1Interface {
	return &fakeroutev1alpha1.FakeRouteV1alpha1{Fake: &c.Fake}
}

// SearchV1alpha1 retrieves the SearchV1alpha1Client
func (c *Clientset) SearchV1alpha1() searchv1alpha1.SearchV1alpha1Interface {
	return &fakesearchv1alpha1.FakeSearchV1alpha1{Fake: &c.Fake}
}

// SecurityV1alpha1 retrieves the SecurityV1alpha1Client
func (c *Clientset) SecurityV1alpha1() securityv1alpha1.SecurityV1alpha1Interface {
	return &fakesecurityv1alpha1.FakeSecurityV1alpha1{Fake: &c.Fake}
}

// SentinelV1alpha1 retrieves the SentinelV1alpha1Client
func (c *Clientset) SentinelV1alpha1() sentinelv1alpha1.SentinelV1alpha1Interface {
	return &fakesentinelv1alpha1.FakeSentinelV1alpha1{Fake: &c.Fake}
}

// ServiceV1alpha1 retrieves the ServiceV1alpha1Client
func (c *Clientset) ServiceV1alpha1() servicev1alpha1.ServiceV1alpha1Interface {
	return &fakeservicev1alpha1.FakeServiceV1alpha1{Fake: &c.Fake}
}

// ServicebusV1alpha1 retrieves the ServicebusV1alpha1Client
func (c *Clientset) ServicebusV1alpha1() servicebusv1alpha1.ServicebusV1alpha1Interface {
	return &fakeservicebusv1alpha1.FakeServicebusV1alpha1{Fake: &c.Fake}
}

// SharedimageV1alpha1 retrieves the SharedimageV1alpha1Client
func (c *Clientset) SharedimageV1alpha1() sharedimagev1alpha1.SharedimageV1alpha1Interface {
	return &fakesharedimagev1alpha1.FakeSharedimageV1alpha1{Fake: &c.Fake}
}

// SignalrV1alpha1 retrieves the SignalrV1alpha1Client
func (c *Clientset) SignalrV1alpha1() signalrv1alpha1.SignalrV1alpha1Interface {
	return &fakesignalrv1alpha1.FakeSignalrV1alpha1{Fake: &c.Fake}
}

// SiterecoveryV1alpha1 retrieves the SiterecoveryV1alpha1Client
func (c *Clientset) SiterecoveryV1alpha1() siterecoveryv1alpha1.SiterecoveryV1alpha1Interface {
	return &fakesiterecoveryv1alpha1.FakeSiterecoveryV1alpha1{Fake: &c.Fake}
}

// SnapshotV1alpha1 retrieves the SnapshotV1alpha1Client
func (c *Clientset) SnapshotV1alpha1() snapshotv1alpha1.SnapshotV1alpha1Interface {
	return &fakesnapshotv1alpha1.FakeSnapshotV1alpha1{Fake: &c.Fake}
}

// SpatialV1alpha1 retrieves the SpatialV1alpha1Client
func (c *Clientset) SpatialV1alpha1() spatialv1alpha1.SpatialV1alpha1Interface {
	return &fakespatialv1alpha1.FakeSpatialV1alpha1{Fake: &c.Fake}
}

// SpringV1alpha1 retrieves the SpringV1alpha1Client
func (c *Clientset) SpringV1alpha1() springv1alpha1.SpringV1alpha1Interface {
	return &fakespringv1alpha1.FakeSpringV1alpha1{Fake: &c.Fake}
}

// SqlV1alpha1 retrieves the SqlV1alpha1Client
func (c *Clientset) SqlV1alpha1() sqlv1alpha1.SqlV1alpha1Interface {
	return &fakesqlv1alpha1.FakeSqlV1alpha1{Fake: &c.Fake}
}

// SshV1alpha1 retrieves the SshV1alpha1Client
func (c *Clientset) SshV1alpha1() sshv1alpha1.SshV1alpha1Interface {
	return &fakesshv1alpha1.FakeSshV1alpha1{Fake: &c.Fake}
}

// StackV1alpha1 retrieves the StackV1alpha1Client
func (c *Clientset) StackV1alpha1() stackv1alpha1.StackV1alpha1Interface {
	return &fakestackv1alpha1.FakeStackV1alpha1{Fake: &c.Fake}
}

// StaticV1alpha1 retrieves the StaticV1alpha1Client
func (c *Clientset) StaticV1alpha1() staticv1alpha1.StaticV1alpha1Interface {
	return &fakestaticv1alpha1.FakeStaticV1alpha1{Fake: &c.Fake}
}

// StorageV1alpha1 retrieves the StorageV1alpha1Client
func (c *Clientset) StorageV1alpha1() storagev1alpha1.StorageV1alpha1Interface {
	return &fakestoragev1alpha1.FakeStorageV1alpha1{Fake: &c.Fake}
}

// StreamV1alpha1 retrieves the StreamV1alpha1Client
func (c *Clientset) StreamV1alpha1() streamv1alpha1.StreamV1alpha1Interface {
	return &fakestreamv1alpha1.FakeStreamV1alpha1{Fake: &c.Fake}
}

// SubnetV1alpha1 retrieves the SubnetV1alpha1Client
func (c *Clientset) SubnetV1alpha1() subnetv1alpha1.SubnetV1alpha1Interface {
	return &fakesubnetv1alpha1.FakeSubnetV1alpha1{Fake: &c.Fake}
}

// SubscriptionV1alpha1 retrieves the SubscriptionV1alpha1Client
func (c *Clientset) SubscriptionV1alpha1() subscriptionv1alpha1.SubscriptionV1alpha1Interface {
	return &fakesubscriptionv1alpha1.FakeSubscriptionV1alpha1{Fake: &c.Fake}
}

// SynapseV1alpha1 retrieves the SynapseV1alpha1Client
func (c *Clientset) SynapseV1alpha1() synapsev1alpha1.SynapseV1alpha1Interface {
	return &fakesynapsev1alpha1.FakeSynapseV1alpha1{Fake: &c.Fake}
}

// TemplateV1alpha1 retrieves the TemplateV1alpha1Client
func (c *Clientset) TemplateV1alpha1() templatev1alpha1.TemplateV1alpha1Interface {
	return &faketemplatev1alpha1.FakeTemplateV1alpha1{Fake: &c.Fake}
}

// TenantV1alpha1 retrieves the TenantV1alpha1Client
func (c *Clientset) TenantV1alpha1() tenantv1alpha1.TenantV1alpha1Interface {
	return &faketenantv1alpha1.FakeTenantV1alpha1{Fake: &c.Fake}
}

// TrafficmanagerV1alpha1 retrieves the TrafficmanagerV1alpha1Client
func (c *Clientset) TrafficmanagerV1alpha1() trafficmanagerv1alpha1.TrafficmanagerV1alpha1Interface {
	return &faketrafficmanagerv1alpha1.FakeTrafficmanagerV1alpha1{Fake: &c.Fake}
}

// UserV1alpha1 retrieves the UserV1alpha1Client
func (c *Clientset) UserV1alpha1() userv1alpha1.UserV1alpha1Interface {
	return &fakeuserv1alpha1.FakeUserV1alpha1{Fake: &c.Fake}
}

// VirtualV1alpha1 retrieves the VirtualV1alpha1Client
func (c *Clientset) VirtualV1alpha1() virtualv1alpha1.VirtualV1alpha1Interface {
	return &fakevirtualv1alpha1.FakeVirtualV1alpha1{Fake: &c.Fake}
}

// VmwareV1alpha1 retrieves the VmwareV1alpha1Client
func (c *Clientset) VmwareV1alpha1() vmwarev1alpha1.VmwareV1alpha1Interface {
	return &fakevmwarev1alpha1.FakeVmwareV1alpha1{Fake: &c.Fake}
}

// VpnV1alpha1 retrieves the VpnV1alpha1Client
func (c *Clientset) VpnV1alpha1() vpnv1alpha1.VpnV1alpha1Interface {
	return &fakevpnv1alpha1.FakeVpnV1alpha1{Fake: &c.Fake}
}

// WebV1alpha1 retrieves the WebV1alpha1Client
func (c *Clientset) WebV1alpha1() webv1alpha1.WebV1alpha1Interface {
	return &fakewebv1alpha1.FakeWebV1alpha1{Fake: &c.Fake}
}

// WindowsV1alpha1 retrieves the WindowsV1alpha1Client
func (c *Clientset) WindowsV1alpha1() windowsv1alpha1.WindowsV1alpha1Interface {
	return &fakewindowsv1alpha1.FakeWindowsV1alpha1{Fake: &c.Fake}
}
