/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/stream/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAnalyticsReferenceInputBlobs implements AnalyticsReferenceInputBlobInterface
type FakeAnalyticsReferenceInputBlobs struct {
	Fake *FakeStreamV1alpha1
	ns   string
}

var analyticsreferenceinputblobsResource = schema.GroupVersionResource{Group: "stream.azurerm.kubeform.com", Version: "v1alpha1", Resource: "analyticsreferenceinputblobs"}

var analyticsreferenceinputblobsKind = schema.GroupVersionKind{Group: "stream.azurerm.kubeform.com", Version: "v1alpha1", Kind: "AnalyticsReferenceInputBlob"}

// Get takes name of the analyticsReferenceInputBlob, and returns the corresponding analyticsReferenceInputBlob object, and an error if there is any.
func (c *FakeAnalyticsReferenceInputBlobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AnalyticsReferenceInputBlob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(analyticsreferenceinputblobsResource, c.ns, name), &v1alpha1.AnalyticsReferenceInputBlob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AnalyticsReferenceInputBlob), err
}

// List takes label and field selectors, and returns the list of AnalyticsReferenceInputBlobs that match those selectors.
func (c *FakeAnalyticsReferenceInputBlobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AnalyticsReferenceInputBlobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(analyticsreferenceinputblobsResource, analyticsreferenceinputblobsKind, c.ns, opts), &v1alpha1.AnalyticsReferenceInputBlobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AnalyticsReferenceInputBlobList{ListMeta: obj.(*v1alpha1.AnalyticsReferenceInputBlobList).ListMeta}
	for _, item := range obj.(*v1alpha1.AnalyticsReferenceInputBlobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested analyticsReferenceInputBlobs.
func (c *FakeAnalyticsReferenceInputBlobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(analyticsreferenceinputblobsResource, c.ns, opts))

}

// Create takes the representation of a analyticsReferenceInputBlob and creates it.  Returns the server's representation of the analyticsReferenceInputBlob, and an error, if there is any.
func (c *FakeAnalyticsReferenceInputBlobs) Create(ctx context.Context, analyticsReferenceInputBlob *v1alpha1.AnalyticsReferenceInputBlob, opts v1.CreateOptions) (result *v1alpha1.AnalyticsReferenceInputBlob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(analyticsreferenceinputblobsResource, c.ns, analyticsReferenceInputBlob), &v1alpha1.AnalyticsReferenceInputBlob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AnalyticsReferenceInputBlob), err
}

// Update takes the representation of a analyticsReferenceInputBlob and updates it. Returns the server's representation of the analyticsReferenceInputBlob, and an error, if there is any.
func (c *FakeAnalyticsReferenceInputBlobs) Update(ctx context.Context, analyticsReferenceInputBlob *v1alpha1.AnalyticsReferenceInputBlob, opts v1.UpdateOptions) (result *v1alpha1.AnalyticsReferenceInputBlob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(analyticsreferenceinputblobsResource, c.ns, analyticsReferenceInputBlob), &v1alpha1.AnalyticsReferenceInputBlob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AnalyticsReferenceInputBlob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAnalyticsReferenceInputBlobs) UpdateStatus(ctx context.Context, analyticsReferenceInputBlob *v1alpha1.AnalyticsReferenceInputBlob, opts v1.UpdateOptions) (*v1alpha1.AnalyticsReferenceInputBlob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(analyticsreferenceinputblobsResource, "status", c.ns, analyticsReferenceInputBlob), &v1alpha1.AnalyticsReferenceInputBlob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AnalyticsReferenceInputBlob), err
}

// Delete takes name of the analyticsReferenceInputBlob and deletes it. Returns an error if one occurs.
func (c *FakeAnalyticsReferenceInputBlobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(analyticsreferenceinputblobsResource, c.ns, name), &v1alpha1.AnalyticsReferenceInputBlob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAnalyticsReferenceInputBlobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(analyticsreferenceinputblobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AnalyticsReferenceInputBlobList{})
	return err
}

// Patch applies the patch and returns the patched analyticsReferenceInputBlob.
func (c *FakeAnalyticsReferenceInputBlobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AnalyticsReferenceInputBlob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(analyticsreferenceinputblobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AnalyticsReferenceInputBlob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AnalyticsReferenceInputBlob), err
}
