/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/stream/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAnalyticsOutputServicebusTopics implements AnalyticsOutputServicebusTopicInterface
type FakeAnalyticsOutputServicebusTopics struct {
	Fake *FakeStreamV1alpha1
	ns   string
}

var analyticsoutputservicebustopicsResource = schema.GroupVersionResource{Group: "stream.azurerm.kubeform.com", Version: "v1alpha1", Resource: "analyticsoutputservicebustopics"}

var analyticsoutputservicebustopicsKind = schema.GroupVersionKind{Group: "stream.azurerm.kubeform.com", Version: "v1alpha1", Kind: "AnalyticsOutputServicebusTopic"}

// Get takes name of the analyticsOutputServicebusTopic, and returns the corresponding analyticsOutputServicebusTopic object, and an error if there is any.
func (c *FakeAnalyticsOutputServicebusTopics) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AnalyticsOutputServicebusTopic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(analyticsoutputservicebustopicsResource, c.ns, name), &v1alpha1.AnalyticsOutputServicebusTopic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AnalyticsOutputServicebusTopic), err
}

// List takes label and field selectors, and returns the list of AnalyticsOutputServicebusTopics that match those selectors.
func (c *FakeAnalyticsOutputServicebusTopics) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AnalyticsOutputServicebusTopicList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(analyticsoutputservicebustopicsResource, analyticsoutputservicebustopicsKind, c.ns, opts), &v1alpha1.AnalyticsOutputServicebusTopicList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AnalyticsOutputServicebusTopicList{ListMeta: obj.(*v1alpha1.AnalyticsOutputServicebusTopicList).ListMeta}
	for _, item := range obj.(*v1alpha1.AnalyticsOutputServicebusTopicList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested analyticsOutputServicebusTopics.
func (c *FakeAnalyticsOutputServicebusTopics) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(analyticsoutputservicebustopicsResource, c.ns, opts))

}

// Create takes the representation of a analyticsOutputServicebusTopic and creates it.  Returns the server's representation of the analyticsOutputServicebusTopic, and an error, if there is any.
func (c *FakeAnalyticsOutputServicebusTopics) Create(ctx context.Context, analyticsOutputServicebusTopic *v1alpha1.AnalyticsOutputServicebusTopic, opts v1.CreateOptions) (result *v1alpha1.AnalyticsOutputServicebusTopic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(analyticsoutputservicebustopicsResource, c.ns, analyticsOutputServicebusTopic), &v1alpha1.AnalyticsOutputServicebusTopic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AnalyticsOutputServicebusTopic), err
}

// Update takes the representation of a analyticsOutputServicebusTopic and updates it. Returns the server's representation of the analyticsOutputServicebusTopic, and an error, if there is any.
func (c *FakeAnalyticsOutputServicebusTopics) Update(ctx context.Context, analyticsOutputServicebusTopic *v1alpha1.AnalyticsOutputServicebusTopic, opts v1.UpdateOptions) (result *v1alpha1.AnalyticsOutputServicebusTopic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(analyticsoutputservicebustopicsResource, c.ns, analyticsOutputServicebusTopic), &v1alpha1.AnalyticsOutputServicebusTopic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AnalyticsOutputServicebusTopic), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAnalyticsOutputServicebusTopics) UpdateStatus(ctx context.Context, analyticsOutputServicebusTopic *v1alpha1.AnalyticsOutputServicebusTopic, opts v1.UpdateOptions) (*v1alpha1.AnalyticsOutputServicebusTopic, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(analyticsoutputservicebustopicsResource, "status", c.ns, analyticsOutputServicebusTopic), &v1alpha1.AnalyticsOutputServicebusTopic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AnalyticsOutputServicebusTopic), err
}

// Delete takes name of the analyticsOutputServicebusTopic and deletes it. Returns an error if one occurs.
func (c *FakeAnalyticsOutputServicebusTopics) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(analyticsoutputservicebustopicsResource, c.ns, name), &v1alpha1.AnalyticsOutputServicebusTopic{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAnalyticsOutputServicebusTopics) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(analyticsoutputservicebustopicsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AnalyticsOutputServicebusTopicList{})
	return err
}

// Patch applies the patch and returns the patched analyticsOutputServicebusTopic.
func (c *FakeAnalyticsOutputServicebusTopics) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AnalyticsOutputServicebusTopic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(analyticsoutputservicebustopicsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AnalyticsOutputServicebusTopic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AnalyticsOutputServicebusTopic), err
}
