/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/mssql/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManagedDatabases implements ManagedDatabaseInterface
type FakeManagedDatabases struct {
	Fake *FakeMssqlV1alpha1
	ns   string
}

var manageddatabasesResource = schema.GroupVersionResource{Group: "mssql.azurerm.kubeform.com", Version: "v1alpha1", Resource: "manageddatabases"}

var manageddatabasesKind = schema.GroupVersionKind{Group: "mssql.azurerm.kubeform.com", Version: "v1alpha1", Kind: "ManagedDatabase"}

// Get takes name of the managedDatabase, and returns the corresponding managedDatabase object, and an error if there is any.
func (c *FakeManagedDatabases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagedDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(manageddatabasesResource, c.ns, name), &v1alpha1.ManagedDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedDatabase), err
}

// List takes label and field selectors, and returns the list of ManagedDatabases that match those selectors.
func (c *FakeManagedDatabases) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagedDatabaseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(manageddatabasesResource, manageddatabasesKind, c.ns, opts), &v1alpha1.ManagedDatabaseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ManagedDatabaseList{ListMeta: obj.(*v1alpha1.ManagedDatabaseList).ListMeta}
	for _, item := range obj.(*v1alpha1.ManagedDatabaseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested managedDatabases.
func (c *FakeManagedDatabases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(manageddatabasesResource, c.ns, opts))

}

// Create takes the representation of a managedDatabase and creates it.  Returns the server's representation of the managedDatabase, and an error, if there is any.
func (c *FakeManagedDatabases) Create(ctx context.Context, managedDatabase *v1alpha1.ManagedDatabase, opts v1.CreateOptions) (result *v1alpha1.ManagedDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(manageddatabasesResource, c.ns, managedDatabase), &v1alpha1.ManagedDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedDatabase), err
}

// Update takes the representation of a managedDatabase and updates it. Returns the server's representation of the managedDatabase, and an error, if there is any.
func (c *FakeManagedDatabases) Update(ctx context.Context, managedDatabase *v1alpha1.ManagedDatabase, opts v1.UpdateOptions) (result *v1alpha1.ManagedDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(manageddatabasesResource, c.ns, managedDatabase), &v1alpha1.ManagedDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedDatabase), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeManagedDatabases) UpdateStatus(ctx context.Context, managedDatabase *v1alpha1.ManagedDatabase, opts v1.UpdateOptions) (*v1alpha1.ManagedDatabase, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(manageddatabasesResource, "status", c.ns, managedDatabase), &v1alpha1.ManagedDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedDatabase), err
}

// Delete takes name of the managedDatabase and deletes it. Returns an error if one occurs.
func (c *FakeManagedDatabases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(manageddatabasesResource, c.ns, name), &v1alpha1.ManagedDatabase{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManagedDatabases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(manageddatabasesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ManagedDatabaseList{})
	return err
}

// Patch applies the patch and returns the patched managedDatabase.
func (c *FakeManagedDatabases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagedDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(manageddatabasesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ManagedDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ManagedDatabase), err
}
