apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: azurerm.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: caches.redis.azurerm.kubeform.com
spec:
  group: redis.azurerm.kubeform.com
  names:
    kind: Cache
    listKind: CacheList
    plural: caches
    singular: cache
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  capacity:
                    format: int64
                    type: integer
                  enableNonSslPort:
                    type: boolean
                  family:
                    type: string
                  hostname:
                    type: string
                  id:
                    type: string
                  location:
                    type: string
                  minimumTlsVersion:
                    type: string
                  name:
                    type: string
                  patchSchedule:
                    items:
                      properties:
                        dayOfWeek:
                          type: string
                        maintenanceWindow:
                          type: string
                        startHourUtc:
                          format: int64
                          type: integer
                      required:
                      - dayOfWeek
                      type: object
                    type: array
                  port:
                    format: int64
                    type: integer
                  privateStaticIPAddress:
                    type: string
                  publicNetworkAccessEnabled:
                    type: boolean
                  redisConfiguration:
                    properties:
                      aofBackupEnabled:
                        type: boolean
                      enableAuthentication:
                        type: boolean
                      maxclients:
                        format: int64
                        type: integer
                      maxfragmentationmemoryReserved:
                        format: int64
                        type: integer
                      maxmemoryDelta:
                        format: int64
                        type: integer
                      maxmemoryPolicy:
                        type: string
                      maxmemoryReserved:
                        format: int64
                        type: integer
                      notifyKeyspaceEvents:
                        type: string
                      rdbBackupEnabled:
                        type: boolean
                      rdbBackupFrequency:
                        format: int64
                        type: integer
                      rdbBackupMaxSnapshotCount:
                        format: int64
                        type: integer
                    type: object
                  redisVersion:
                    type: string
                  replicasPerMaster:
                    format: int64
                    type: integer
                  replicasPerPrimary:
                    format: int64
                    type: integer
                  resourceGroupName:
                    type: string
                  shardCount:
                    format: int64
                    type: integer
                  skuName:
                    type: string
                  sslPort:
                    format: int64
                    type: integer
                  subnetID:
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  tenantSettings:
                    additionalProperties:
                      type: string
                    type: object
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  zones:
                    items:
                      type: string
                    minItems: 1
                    type: array
                required:
                - capacity
                - family
                - location
                - name
                - resourceGroupName
                - skuName
                type: object
              secretRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              state:
                properties:
                  capacity:
                    format: int64
                    type: integer
                  enableNonSslPort:
                    type: boolean
                  family:
                    type: string
                  hostname:
                    type: string
                  id:
                    type: string
                  location:
                    type: string
                  minimumTlsVersion:
                    type: string
                  name:
                    type: string
                  patchSchedule:
                    items:
                      properties:
                        dayOfWeek:
                          type: string
                        maintenanceWindow:
                          type: string
                        startHourUtc:
                          format: int64
                          type: integer
                      required:
                      - dayOfWeek
                      type: object
                    type: array
                  port:
                    format: int64
                    type: integer
                  privateStaticIPAddress:
                    type: string
                  publicNetworkAccessEnabled:
                    type: boolean
                  redisConfiguration:
                    properties:
                      aofBackupEnabled:
                        type: boolean
                      enableAuthentication:
                        type: boolean
                      maxclients:
                        format: int64
                        type: integer
                      maxfragmentationmemoryReserved:
                        format: int64
                        type: integer
                      maxmemoryDelta:
                        format: int64
                        type: integer
                      maxmemoryPolicy:
                        type: string
                      maxmemoryReserved:
                        format: int64
                        type: integer
                      notifyKeyspaceEvents:
                        type: string
                      rdbBackupEnabled:
                        type: boolean
                      rdbBackupFrequency:
                        format: int64
                        type: integer
                      rdbBackupMaxSnapshotCount:
                        format: int64
                        type: integer
                    type: object
                  redisVersion:
                    type: string
                  replicasPerMaster:
                    format: int64
                    type: integer
                  replicasPerPrimary:
                    format: int64
                    type: integer
                  resourceGroupName:
                    type: string
                  shardCount:
                    format: int64
                    type: integer
                  skuName:
                    type: string
                  sslPort:
                    format: int64
                    type: integer
                  subnetID:
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  tenantSettings:
                    additionalProperties:
                      type: string
                    type: object
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  zones:
                    items:
                      type: string
                    minItems: 1
                    type: array
                required:
                - capacity
                - family
                - location
                - name
                - resourceGroupName
                - skuName
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
