/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// NatGatewayAssociationListerExpansion allows custom methods to be added to
// NatGatewayAssociationLister.
type NatGatewayAssociationListerExpansion interface{}

// NatGatewayAssociationNamespaceListerExpansion allows custom methods to be added to
// NatGatewayAssociationNamespaceLister.
type NatGatewayAssociationNamespaceListerExpansion interface{}

// NetworkSecurityGroupAssociationListerExpansion allows custom methods to be added to
// NetworkSecurityGroupAssociationLister.
type NetworkSecurityGroupAssociationListerExpansion interface{}

// NetworkSecurityGroupAssociationNamespaceListerExpansion allows custom methods to be added to
// NetworkSecurityGroupAssociationNamespaceLister.
type NetworkSecurityGroupAssociationNamespaceListerExpansion interface{}

// RouteTableAssociationListerExpansion allows custom methods to be added to
// RouteTableAssociationLister.
type RouteTableAssociationListerExpansion interface{}

// RouteTableAssociationNamespaceListerExpansion allows custom methods to be added to
// RouteTableAssociationNamespaceLister.
type RouteTableAssociationNamespaceListerExpansion interface{}

// ServiceEndpointStoragePolicyListerExpansion allows custom methods to be added to
// ServiceEndpointStoragePolicyLister.
type ServiceEndpointStoragePolicyListerExpansion interface{}

// ServiceEndpointStoragePolicyNamespaceListerExpansion allows custom methods to be added to
// ServiceEndpointStoragePolicyNamespaceLister.
type ServiceEndpointStoragePolicyNamespaceListerExpansion interface{}

// SubnetListerExpansion allows custom methods to be added to
// SubnetLister.
type SubnetListerExpansion interface{}

// SubnetNamespaceListerExpansion allows custom methods to be added to
// SubnetNamespaceLister.
type SubnetNamespaceListerExpansion interface{}
