/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/loganalytics/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSavedSearches implements SavedSearchInterface
type FakeSavedSearches struct {
	Fake *FakeLoganalyticsV1alpha1
	ns   string
}

var savedsearchesResource = schema.GroupVersionResource{Group: "loganalytics.azurerm.kubeform.com", Version: "v1alpha1", Resource: "savedsearches"}

var savedsearchesKind = schema.GroupVersionKind{Group: "loganalytics.azurerm.kubeform.com", Version: "v1alpha1", Kind: "SavedSearch"}

// Get takes name of the savedSearch, and returns the corresponding savedSearch object, and an error if there is any.
func (c *FakeSavedSearches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SavedSearch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(savedsearchesResource, c.ns, name), &v1alpha1.SavedSearch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SavedSearch), err
}

// List takes label and field selectors, and returns the list of SavedSearches that match those selectors.
func (c *FakeSavedSearches) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SavedSearchList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(savedsearchesResource, savedsearchesKind, c.ns, opts), &v1alpha1.SavedSearchList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SavedSearchList{ListMeta: obj.(*v1alpha1.SavedSearchList).ListMeta}
	for _, item := range obj.(*v1alpha1.SavedSearchList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested savedSearches.
func (c *FakeSavedSearches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(savedsearchesResource, c.ns, opts))

}

// Create takes the representation of a savedSearch and creates it.  Returns the server's representation of the savedSearch, and an error, if there is any.
func (c *FakeSavedSearches) Create(ctx context.Context, savedSearch *v1alpha1.SavedSearch, opts v1.CreateOptions) (result *v1alpha1.SavedSearch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(savedsearchesResource, c.ns, savedSearch), &v1alpha1.SavedSearch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SavedSearch), err
}

// Update takes the representation of a savedSearch and updates it. Returns the server's representation of the savedSearch, and an error, if there is any.
func (c *FakeSavedSearches) Update(ctx context.Context, savedSearch *v1alpha1.SavedSearch, opts v1.UpdateOptions) (result *v1alpha1.SavedSearch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(savedsearchesResource, c.ns, savedSearch), &v1alpha1.SavedSearch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SavedSearch), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSavedSearches) UpdateStatus(ctx context.Context, savedSearch *v1alpha1.SavedSearch, opts v1.UpdateOptions) (*v1alpha1.SavedSearch, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(savedsearchesResource, "status", c.ns, savedSearch), &v1alpha1.SavedSearch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SavedSearch), err
}

// Delete takes name of the savedSearch and deletes it. Returns an error if one occurs.
func (c *FakeSavedSearches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(savedsearchesResource, c.ns, name), &v1alpha1.SavedSearch{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSavedSearches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(savedsearchesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SavedSearchList{})
	return err
}

// Patch applies the patch and returns the patched savedSearch.
func (c *FakeSavedSearches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SavedSearch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(savedsearchesResource, c.ns, name, pt, data, subresources...), &v1alpha1.SavedSearch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SavedSearch), err
}
