/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/redis/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEnterpriseDatabases implements EnterpriseDatabaseInterface
type FakeEnterpriseDatabases struct {
	Fake *FakeRedisV1alpha1
	ns   string
}

var enterprisedatabasesResource = schema.GroupVersionResource{Group: "redis.azurerm.kubeform.com", Version: "v1alpha1", Resource: "enterprisedatabases"}

var enterprisedatabasesKind = schema.GroupVersionKind{Group: "redis.azurerm.kubeform.com", Version: "v1alpha1", Kind: "EnterpriseDatabase"}

// Get takes name of the enterpriseDatabase, and returns the corresponding enterpriseDatabase object, and an error if there is any.
func (c *FakeEnterpriseDatabases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.EnterpriseDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(enterprisedatabasesResource, c.ns, name), &v1alpha1.EnterpriseDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnterpriseDatabase), err
}

// List takes label and field selectors, and returns the list of EnterpriseDatabases that match those selectors.
func (c *FakeEnterpriseDatabases) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EnterpriseDatabaseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(enterprisedatabasesResource, enterprisedatabasesKind, c.ns, opts), &v1alpha1.EnterpriseDatabaseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EnterpriseDatabaseList{ListMeta: obj.(*v1alpha1.EnterpriseDatabaseList).ListMeta}
	for _, item := range obj.(*v1alpha1.EnterpriseDatabaseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested enterpriseDatabases.
func (c *FakeEnterpriseDatabases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(enterprisedatabasesResource, c.ns, opts))

}

// Create takes the representation of a enterpriseDatabase and creates it.  Returns the server's representation of the enterpriseDatabase, and an error, if there is any.
func (c *FakeEnterpriseDatabases) Create(ctx context.Context, enterpriseDatabase *v1alpha1.EnterpriseDatabase, opts v1.CreateOptions) (result *v1alpha1.EnterpriseDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(enterprisedatabasesResource, c.ns, enterpriseDatabase), &v1alpha1.EnterpriseDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnterpriseDatabase), err
}

// Update takes the representation of a enterpriseDatabase and updates it. Returns the server's representation of the enterpriseDatabase, and an error, if there is any.
func (c *FakeEnterpriseDatabases) Update(ctx context.Context, enterpriseDatabase *v1alpha1.EnterpriseDatabase, opts v1.UpdateOptions) (result *v1alpha1.EnterpriseDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(enterprisedatabasesResource, c.ns, enterpriseDatabase), &v1alpha1.EnterpriseDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnterpriseDatabase), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEnterpriseDatabases) UpdateStatus(ctx context.Context, enterpriseDatabase *v1alpha1.EnterpriseDatabase, opts v1.UpdateOptions) (*v1alpha1.EnterpriseDatabase, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(enterprisedatabasesResource, "status", c.ns, enterpriseDatabase), &v1alpha1.EnterpriseDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnterpriseDatabase), err
}

// Delete takes name of the enterpriseDatabase and deletes it. Returns an error if one occurs.
func (c *FakeEnterpriseDatabases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(enterprisedatabasesResource, c.ns, name), &v1alpha1.EnterpriseDatabase{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEnterpriseDatabases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(enterprisedatabasesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EnterpriseDatabaseList{})
	return err
}

// Patch applies the patch and returns the patched enterpriseDatabase.
func (c *FakeEnterpriseDatabases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.EnterpriseDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(enterprisedatabasesResource, c.ns, name, pt, data, subresources...), &v1alpha1.EnterpriseDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnterpriseDatabase), err
}
