/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/vmware/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeExpressRouteAuthorizations implements ExpressRouteAuthorizationInterface
type FakeExpressRouteAuthorizations struct {
	Fake *FakeVmwareV1alpha1
	ns   string
}

var expressrouteauthorizationsResource = schema.GroupVersionResource{Group: "vmware.azurerm.kubeform.com", Version: "v1alpha1", Resource: "expressrouteauthorizations"}

var expressrouteauthorizationsKind = schema.GroupVersionKind{Group: "vmware.azurerm.kubeform.com", Version: "v1alpha1", Kind: "ExpressRouteAuthorization"}

// Get takes name of the expressRouteAuthorization, and returns the corresponding expressRouteAuthorization object, and an error if there is any.
func (c *FakeExpressRouteAuthorizations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ExpressRouteAuthorization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(expressrouteauthorizationsResource, c.ns, name), &v1alpha1.ExpressRouteAuthorization{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExpressRouteAuthorization), err
}

// List takes label and field selectors, and returns the list of ExpressRouteAuthorizations that match those selectors.
func (c *FakeExpressRouteAuthorizations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ExpressRouteAuthorizationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(expressrouteauthorizationsResource, expressrouteauthorizationsKind, c.ns, opts), &v1alpha1.ExpressRouteAuthorizationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ExpressRouteAuthorizationList{ListMeta: obj.(*v1alpha1.ExpressRouteAuthorizationList).ListMeta}
	for _, item := range obj.(*v1alpha1.ExpressRouteAuthorizationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested expressRouteAuthorizations.
func (c *FakeExpressRouteAuthorizations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(expressrouteauthorizationsResource, c.ns, opts))

}

// Create takes the representation of a expressRouteAuthorization and creates it.  Returns the server's representation of the expressRouteAuthorization, and an error, if there is any.
func (c *FakeExpressRouteAuthorizations) Create(ctx context.Context, expressRouteAuthorization *v1alpha1.ExpressRouteAuthorization, opts v1.CreateOptions) (result *v1alpha1.ExpressRouteAuthorization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(expressrouteauthorizationsResource, c.ns, expressRouteAuthorization), &v1alpha1.ExpressRouteAuthorization{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExpressRouteAuthorization), err
}

// Update takes the representation of a expressRouteAuthorization and updates it. Returns the server's representation of the expressRouteAuthorization, and an error, if there is any.
func (c *FakeExpressRouteAuthorizations) Update(ctx context.Context, expressRouteAuthorization *v1alpha1.ExpressRouteAuthorization, opts v1.UpdateOptions) (result *v1alpha1.ExpressRouteAuthorization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(expressrouteauthorizationsResource, c.ns, expressRouteAuthorization), &v1alpha1.ExpressRouteAuthorization{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExpressRouteAuthorization), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeExpressRouteAuthorizations) UpdateStatus(ctx context.Context, expressRouteAuthorization *v1alpha1.ExpressRouteAuthorization, opts v1.UpdateOptions) (*v1alpha1.ExpressRouteAuthorization, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(expressrouteauthorizationsResource, "status", c.ns, expressRouteAuthorization), &v1alpha1.ExpressRouteAuthorization{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExpressRouteAuthorization), err
}

// Delete takes name of the expressRouteAuthorization and deletes it. Returns an error if one occurs.
func (c *FakeExpressRouteAuthorizations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(expressrouteauthorizationsResource, c.ns, name), &v1alpha1.ExpressRouteAuthorization{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeExpressRouteAuthorizations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(expressrouteauthorizationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ExpressRouteAuthorizationList{})
	return err
}

// Patch applies the patch and returns the patched expressRouteAuthorization.
func (c *FakeExpressRouteAuthorizations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ExpressRouteAuthorization, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(expressrouteauthorizationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ExpressRouteAuthorization{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ExpressRouteAuthorization), err
}
