/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-azurerm-api/apis/advanced/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeThreatProtections implements ThreatProtectionInterface
type FakeThreatProtections struct {
	Fake *FakeAdvancedV1alpha1
	ns   string
}

var threatprotectionsResource = schema.GroupVersionResource{Group: "advanced.azurerm.kubeform.com", Version: "v1alpha1", Resource: "threatprotections"}

var threatprotectionsKind = schema.GroupVersionKind{Group: "advanced.azurerm.kubeform.com", Version: "v1alpha1", Kind: "ThreatProtection"}

// Get takes name of the threatProtection, and returns the corresponding threatProtection object, and an error if there is any.
func (c *FakeThreatProtections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ThreatProtection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(threatprotectionsResource, c.ns, name), &v1alpha1.ThreatProtection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThreatProtection), err
}

// List takes label and field selectors, and returns the list of ThreatProtections that match those selectors.
func (c *FakeThreatProtections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ThreatProtectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(threatprotectionsResource, threatprotectionsKind, c.ns, opts), &v1alpha1.ThreatProtectionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ThreatProtectionList{ListMeta: obj.(*v1alpha1.ThreatProtectionList).ListMeta}
	for _, item := range obj.(*v1alpha1.ThreatProtectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested threatProtections.
func (c *FakeThreatProtections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(threatprotectionsResource, c.ns, opts))

}

// Create takes the representation of a threatProtection and creates it.  Returns the server's representation of the threatProtection, and an error, if there is any.
func (c *FakeThreatProtections) Create(ctx context.Context, threatProtection *v1alpha1.ThreatProtection, opts v1.CreateOptions) (result *v1alpha1.ThreatProtection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(threatprotectionsResource, c.ns, threatProtection), &v1alpha1.ThreatProtection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThreatProtection), err
}

// Update takes the representation of a threatProtection and updates it. Returns the server's representation of the threatProtection, and an error, if there is any.
func (c *FakeThreatProtections) Update(ctx context.Context, threatProtection *v1alpha1.ThreatProtection, opts v1.UpdateOptions) (result *v1alpha1.ThreatProtection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(threatprotectionsResource, c.ns, threatProtection), &v1alpha1.ThreatProtection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThreatProtection), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeThreatProtections) UpdateStatus(ctx context.Context, threatProtection *v1alpha1.ThreatProtection, opts v1.UpdateOptions) (*v1alpha1.ThreatProtection, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(threatprotectionsResource, "status", c.ns, threatProtection), &v1alpha1.ThreatProtection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThreatProtection), err
}

// Delete takes name of the threatProtection and deletes it. Returns an error if one occurs.
func (c *FakeThreatProtections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(threatprotectionsResource, c.ns, name), &v1alpha1.ThreatProtection{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeThreatProtections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(threatprotectionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ThreatProtectionList{})
	return err
}

// Patch applies the patch and returns the patched threatProtection.
func (c *FakeThreatProtections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ThreatProtection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(threatprotectionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ThreatProtection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ThreatProtection), err
}
