/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DatabaseListerExpansion allows custom methods to be added to
// DatabaseLister.
type DatabaseListerExpansion interface{}

// DatabaseNamespaceListerExpansion allows custom methods to be added to
// DatabaseNamespaceLister.
type DatabaseNamespaceListerExpansion interface{}

// DatabaseExtendedAuditingPolicyListerExpansion allows custom methods to be added to
// DatabaseExtendedAuditingPolicyLister.
type DatabaseExtendedAuditingPolicyListerExpansion interface{}

// DatabaseExtendedAuditingPolicyNamespaceListerExpansion allows custom methods to be added to
// DatabaseExtendedAuditingPolicyNamespaceLister.
type DatabaseExtendedAuditingPolicyNamespaceListerExpansion interface{}

// DatabaseVulnerabilityAssessmentRuleBaselineListerExpansion allows custom methods to be added to
// DatabaseVulnerabilityAssessmentRuleBaselineLister.
type DatabaseVulnerabilityAssessmentRuleBaselineListerExpansion interface{}

// DatabaseVulnerabilityAssessmentRuleBaselineNamespaceListerExpansion allows custom methods to be added to
// DatabaseVulnerabilityAssessmentRuleBaselineNamespaceLister.
type DatabaseVulnerabilityAssessmentRuleBaselineNamespaceListerExpansion interface{}

// ElasticpoolListerExpansion allows custom methods to be added to
// ElasticpoolLister.
type ElasticpoolListerExpansion interface{}

// ElasticpoolNamespaceListerExpansion allows custom methods to be added to
// ElasticpoolNamespaceLister.
type ElasticpoolNamespaceListerExpansion interface{}

// FirewallRuleListerExpansion allows custom methods to be added to
// FirewallRuleLister.
type FirewallRuleListerExpansion interface{}

// FirewallRuleNamespaceListerExpansion allows custom methods to be added to
// FirewallRuleNamespaceLister.
type FirewallRuleNamespaceListerExpansion interface{}

// JobAgentListerExpansion allows custom methods to be added to
// JobAgentLister.
type JobAgentListerExpansion interface{}

// JobAgentNamespaceListerExpansion allows custom methods to be added to
// JobAgentNamespaceLister.
type JobAgentNamespaceListerExpansion interface{}

// JobCredentialListerExpansion allows custom methods to be added to
// JobCredentialLister.
type JobCredentialListerExpansion interface{}

// JobCredentialNamespaceListerExpansion allows custom methods to be added to
// JobCredentialNamespaceLister.
type JobCredentialNamespaceListerExpansion interface{}

// ServerListerExpansion allows custom methods to be added to
// ServerLister.
type ServerListerExpansion interface{}

// ServerNamespaceListerExpansion allows custom methods to be added to
// ServerNamespaceLister.
type ServerNamespaceListerExpansion interface{}

// ServerExtendedAuditingPolicyListerExpansion allows custom methods to be added to
// ServerExtendedAuditingPolicyLister.
type ServerExtendedAuditingPolicyListerExpansion interface{}

// ServerExtendedAuditingPolicyNamespaceListerExpansion allows custom methods to be added to
// ServerExtendedAuditingPolicyNamespaceLister.
type ServerExtendedAuditingPolicyNamespaceListerExpansion interface{}

// ServerSecurityAlertPolicyListerExpansion allows custom methods to be added to
// ServerSecurityAlertPolicyLister.
type ServerSecurityAlertPolicyListerExpansion interface{}

// ServerSecurityAlertPolicyNamespaceListerExpansion allows custom methods to be added to
// ServerSecurityAlertPolicyNamespaceLister.
type ServerSecurityAlertPolicyNamespaceListerExpansion interface{}

// ServerTransparentDataEncryptionListerExpansion allows custom methods to be added to
// ServerTransparentDataEncryptionLister.
type ServerTransparentDataEncryptionListerExpansion interface{}

// ServerTransparentDataEncryptionNamespaceListerExpansion allows custom methods to be added to
// ServerTransparentDataEncryptionNamespaceLister.
type ServerTransparentDataEncryptionNamespaceListerExpansion interface{}

// ServerVulnerabilityAssessmentListerExpansion allows custom methods to be added to
// ServerVulnerabilityAssessmentLister.
type ServerVulnerabilityAssessmentListerExpansion interface{}

// ServerVulnerabilityAssessmentNamespaceListerExpansion allows custom methods to be added to
// ServerVulnerabilityAssessmentNamespaceLister.
type ServerVulnerabilityAssessmentNamespaceListerExpansion interface{}

// VirtualMachineListerExpansion allows custom methods to be added to
// VirtualMachineLister.
type VirtualMachineListerExpansion interface{}

// VirtualMachineNamespaceListerExpansion allows custom methods to be added to
// VirtualMachineNamespaceLister.
type VirtualMachineNamespaceListerExpansion interface{}

// VirtualNetworkRuleListerExpansion allows custom methods to be added to
// VirtualNetworkRuleLister.
type VirtualNetworkRuleListerExpansion interface{}

// VirtualNetworkRuleNamespaceListerExpansion allows custom methods to be added to
// VirtualNetworkRuleNamespaceLister.
type VirtualNetworkRuleNamespaceListerExpansion interface{}
